sat
(
  (define-fun N1_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N2_E_m1r0c0_m1r1c0 () Bool
    true)
  (define-fun N1_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N2_E_m1r1c0_m1r2c0 () Bool
    true)
  (define-fun N1_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N2_E_m1r2c0_m1r3c0 () Bool
    true)
  (define-fun N1_E_m1r0c2_m1r1c2 () Bool
    false)
  (define-fun N2_E_m1r0c2_m1r1c2 () Bool
    false)
  (define-fun N1_E_m1r1c2_m1r2c2 () Bool
    false)
  (define-fun N2_E_m1r1c2_m1r2c2 () Bool
    false)
  (define-fun N1_E_m1r2c2_m1r3c2 () Bool
    false)
  (define-fun N2_E_m1r2c2_m1r3c2 () Bool
    false)
  (define-fun N1_E_m1r0c4_m1r1c4 () Bool
    false)
  (define-fun N2_E_m1r0c4_m1r1c4 () Bool
    false)
  (define-fun N1_E_m1r1c4_m1r2c4 () Bool
    false)
  (define-fun N2_E_m1r1c4_m1r2c4 () Bool
    false)
  (define-fun N1_E_m1r2c4_m1r3c4 () Bool
    false)
  (define-fun N2_E_m1r2c4_m1r3c4 () Bool
    false)
  (define-fun N1_E_m1r0c6_m1r1c6 () Bool
    false)
  (define-fun N2_E_m1r0c6_m1r1c6 () Bool
    false)
  (define-fun N1_E_m1r1c6_m1r2c6 () Bool
    false)
  (define-fun N2_E_m1r1c6_m1r2c6 () Bool
    false)
  (define-fun N1_E_m1r2c6_m1r3c6 () Bool
    false)
  (define-fun N2_E_m1r2c6_m1r3c6 () Bool
    false)
  (define-fun N1_C0_E_m3r1c0_pinSON () Bool
    false)
  (define-fun N1_C0_E_m3r2c0_pinSON () Bool
    false)
  (define-fun N2_C0_E_m3r1c0_pinSON () Bool
    false)
  (define-fun N2_C0_E_m3r2c0_pinSON () Bool
    false)
  (define-fun N1_C0_E_m3r1c2_pinSON () Bool
    false)
  (define-fun N1_C0_E_m3r2c2_pinSON () Bool
    false)
  (define-fun N2_C0_E_m3r1c2_pinSON () Bool
    false)
  (define-fun N2_C0_E_m3r2c2_pinSON () Bool
    true)
  (define-fun N1_C0_E_m3r1c4_pinSON () Bool
    false)
  (define-fun N1_C0_E_m3r2c4_pinSON () Bool
    false)
  (define-fun N2_C0_E_m3r1c4_pinSON () Bool
    false)
  (define-fun N2_C0_E_m3r2c4_pinSON () Bool
    false)
  (define-fun N1_C0_E_m3r1c6_pinSON () Bool
    false)
  (define-fun N1_C0_E_m3r2c6_pinSON () Bool
    true)
  (define-fun N2_C0_E_m3r1c6_pinSON () Bool
    false)
  (define-fun N2_C0_E_m3r2c6_pinSON () Bool
    false)
  (define-fun N1_C1_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N1_C1_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N1_C1_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N1_C1_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N1_C1_E_m1r0c2_m2r0c2 () Bool
    false)
  (define-fun N1_C1_E_m1r0c3_m1r1c3 () Bool
    false)
  (define-fun N1_C1_E_m1r0c3_m2r0c3 () Bool
    false)
  (define-fun N1_C1_E_m1r0c4_m1r1c4 () Bool
    false)
  (define-fun N1_C1_E_m1r0c4_m2r0c4 () Bool
    false)
  (define-fun N1_C1_E_m1r0c5_m1r1c5 () Bool
    false)
  (define-fun N1_C1_E_m1r0c5_m2r0c5 () Bool
    false)
  (define-fun N1_C1_E_m1r0c6_m1r1c6 () Bool
    false)
  (define-fun N1_C1_E_m1r0c6_m2r0c6 () Bool
    false)
  (define-fun N1_C1_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N1_C1_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N1_C1_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N1_C1_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N1_C1_E_m1r1c2_m2r1c2 () Bool
    false)
  (define-fun N1_C1_E_m1r1c3_m1r2c3 () Bool
    false)
  (define-fun N1_C1_E_m1r1c3_m2r1c3 () Bool
    false)
  (define-fun N1_C1_E_m1r1c4_m1r2c4 () Bool
    false)
  (define-fun N1_C1_E_m1r1c4_m2r1c4 () Bool
    false)
  (define-fun N1_C1_E_m1r1c5_m1r2c5 () Bool
    false)
  (define-fun N1_C1_E_m1r1c5_m2r1c5 () Bool
    false)
  (define-fun N1_C1_E_m1r1c6_m1r2c6 () Bool
    false)
  (define-fun N1_C1_E_m1r1c6_m2r1c6 () Bool
    false)
  (define-fun N1_C1_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N1_C1_E_m1r2c0_m2r2c0 () Bool
    false)
  (define-fun N1_C1_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N1_C1_E_m1r2c1_m2r2c1 () Bool
    false)
  (define-fun N1_C1_E_m1r2c2_m2r2c2 () Bool
    false)
  (define-fun N1_C1_E_m1r2c3_m1r3c3 () Bool
    false)
  (define-fun N1_C1_E_m1r2c3_m2r2c3 () Bool
    false)
  (define-fun N1_C1_E_m1r2c4_m1r3c4 () Bool
    false)
  (define-fun N1_C1_E_m1r2c4_m2r2c4 () Bool
    false)
  (define-fun N1_C1_E_m1r2c5_m1r3c5 () Bool
    false)
  (define-fun N1_C1_E_m1r2c5_m2r2c5 () Bool
    false)
  (define-fun N1_C1_E_m1r2c6_m1r3c6 () Bool
    false)
  (define-fun N1_C1_E_m1r2c6_m2r2c6 () Bool
    false)
  (define-fun N1_C1_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N1_C1_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N1_C1_E_m1r3c2_m2r3c2 () Bool
    true)
  (define-fun N1_C1_E_m1r3c3_m2r3c3 () Bool
    false)
  (define-fun N1_C1_E_m1r3c4_m2r3c4 () Bool
    true)
  (define-fun N1_C1_E_m1r3c5_m2r3c5 () Bool
    false)
  (define-fun N1_C1_E_m1r3c6_m2r3c6 () Bool
    false)
  (define-fun N1_C1_E_m2r0c0_m2r0c1 () Bool
    false)
  (define-fun N1_C1_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N1_C1_E_m2r0c1_m2r0c2 () Bool
    false)
  (define-fun N1_C1_E_m2r0c2_m2r0c3 () Bool
    false)
  (define-fun N1_C1_E_m2r0c2_m3r0c2 () Bool
    false)
  (define-fun N1_C1_E_m2r0c3_m2r0c4 () Bool
    false)
  (define-fun N1_C1_E_m2r0c4_m2r0c5 () Bool
    false)
  (define-fun N1_C1_E_m2r0c4_m3r0c4 () Bool
    false)
  (define-fun N1_C1_E_m2r0c5_m2r0c6 () Bool
    false)
  (define-fun N1_C1_E_m2r0c6_m3r0c6 () Bool
    false)
  (define-fun N1_C1_E_m2r1c0_m2r1c1 () Bool
    false)
  (define-fun N1_C1_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N1_C1_E_m2r1c1_m2r1c2 () Bool
    false)
  (define-fun N1_C1_E_m2r1c2_m2r1c3 () Bool
    false)
  (define-fun N1_C1_E_m2r1c2_m3r1c2 () Bool
    false)
  (define-fun N1_C1_E_m2r1c3_m2r1c4 () Bool
    false)
  (define-fun N1_C1_E_m2r1c4_m2r1c5 () Bool
    false)
  (define-fun N1_C1_E_m2r1c4_m3r1c4 () Bool
    false)
  (define-fun N1_C1_E_m2r1c5_m2r1c6 () Bool
    false)
  (define-fun N1_C1_E_m2r1c6_m3r1c6 () Bool
    false)
  (define-fun N1_C1_E_m2r2c0_m2r2c1 () Bool
    false)
  (define-fun N1_C1_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N1_C1_E_m2r2c1_m2r2c2 () Bool
    false)
  (define-fun N1_C1_E_m2r2c2_m2r2c3 () Bool
    false)
  (define-fun N1_C1_E_m2r2c2_m3r2c2 () Bool
    false)
  (define-fun N1_C1_E_m2r2c3_m2r2c4 () Bool
    false)
  (define-fun N1_C1_E_m2r2c4_m2r2c5 () Bool
    false)
  (define-fun N1_C1_E_m2r2c4_m3r2c4 () Bool
    false)
  (define-fun N1_C1_E_m2r2c5_m2r2c6 () Bool
    false)
  (define-fun N1_C1_E_m2r2c6_m3r2c6 () Bool
    false)
  (define-fun N1_C1_E_m2r3c0_m2r3c1 () Bool
    false)
  (define-fun N1_C1_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N1_C1_E_m2r3c1_m2r3c2 () Bool
    false)
  (define-fun N1_C1_E_m2r3c2_m2r3c3 () Bool
    true)
  (define-fun N1_C1_E_m2r3c2_m3r3c2 () Bool
    false)
  (define-fun N1_C1_E_m2r3c3_m2r3c4 () Bool
    true)
  (define-fun N1_C1_E_m2r3c4_m2r3c5 () Bool
    false)
  (define-fun N1_C1_E_m2r3c4_m3r3c4 () Bool
    false)
  (define-fun N1_C1_E_m2r3c5_m2r3c6 () Bool
    false)
  (define-fun N1_C1_E_m2r3c6_m3r3c6 () Bool
    false)
  (define-fun N1_C1_E_m3r0c0_m3r1c0 () Bool
    false)
  (define-fun N1_C1_E_m3r0c0_m4r0c0 () Bool
    false)
  (define-fun N1_C1_E_m3r0c2_m3r1c2 () Bool
    false)
  (define-fun N1_C1_E_m3r0c2_m4r0c2 () Bool
    false)
  (define-fun N1_C1_E_m3r0c4_m3r1c4 () Bool
    false)
  (define-fun N1_C1_E_m3r0c4_m4r0c4 () Bool
    false)
  (define-fun N1_C1_E_m3r0c6_m3r1c6 () Bool
    false)
  (define-fun N1_C1_E_m3r0c6_m4r0c6 () Bool
    false)
  (define-fun N1_C1_E_m3r1c0_m3r2c0 () Bool
    false)
  (define-fun N1_C1_E_m3r1c0_m4r1c0 () Bool
    false)
  (define-fun N1_C1_E_m3r1c2_m3r2c2 () Bool
    false)
  (define-fun N1_C1_E_m3r1c2_m4r1c2 () Bool
    false)
  (define-fun N1_C1_E_m3r1c4_m3r2c4 () Bool
    false)
  (define-fun N1_C1_E_m3r1c4_m4r1c4 () Bool
    false)
  (define-fun N1_C1_E_m3r1c6_m3r2c6 () Bool
    false)
  (define-fun N1_C1_E_m3r1c6_m4r1c6 () Bool
    false)
  (define-fun N1_C1_E_m3r2c0_m3r3c0 () Bool
    false)
  (define-fun N1_C1_E_m3r2c0_m4r2c0 () Bool
    false)
  (define-fun N1_C1_E_m3r2c2_m3r3c2 () Bool
    false)
  (define-fun N1_C1_E_m3r2c2_m4r2c2 () Bool
    false)
  (define-fun N1_C1_E_m3r2c4_m3r3c4 () Bool
    false)
  (define-fun N1_C1_E_m3r2c4_m4r2c4 () Bool
    false)
  (define-fun N1_C1_E_m3r2c6_m3r3c6 () Bool
    false)
  (define-fun N1_C1_E_m3r2c6_m4r2c6 () Bool
    false)
  (define-fun N1_C1_E_m3r3c0_m4r3c0 () Bool
    false)
  (define-fun N1_C1_E_m3r3c2_m4r3c2 () Bool
    false)
  (define-fun N1_C1_E_m3r3c4_m4r3c4 () Bool
    false)
  (define-fun N1_C1_E_m3r3c6_m4r3c6 () Bool
    false)
  (define-fun N1_C1_E_m4r0c0_m4r0c1 () Bool
    false)
  (define-fun N1_C1_E_m4r0c1_m4r0c2 () Bool
    false)
  (define-fun N1_C1_E_m4r0c2_m4r0c3 () Bool
    false)
  (define-fun N1_C1_E_m4r0c3_m4r0c4 () Bool
    false)
  (define-fun N1_C1_E_m4r0c4_m4r0c5 () Bool
    false)
  (define-fun N1_C1_E_m4r0c5_m4r0c6 () Bool
    false)
  (define-fun N1_C1_E_m4r1c0_m4r1c1 () Bool
    false)
  (define-fun N1_C1_E_m4r1c1_m4r1c2 () Bool
    false)
  (define-fun N1_C1_E_m4r1c2_m4r1c3 () Bool
    false)
  (define-fun N1_C1_E_m4r1c3_m4r1c4 () Bool
    false)
  (define-fun N1_C1_E_m4r1c4_m4r1c5 () Bool
    false)
  (define-fun N1_C1_E_m4r1c5_m4r1c6 () Bool
    false)
  (define-fun N1_C1_E_m4r2c0_m4r2c1 () Bool
    false)
  (define-fun N1_C1_E_m4r2c1_m4r2c2 () Bool
    false)
  (define-fun N1_C1_E_m4r2c2_m4r2c3 () Bool
    false)
  (define-fun N1_C1_E_m4r2c3_m4r2c4 () Bool
    false)
  (define-fun N1_C1_E_m4r2c4_m4r2c5 () Bool
    false)
  (define-fun N1_C1_E_m4r2c5_m4r2c6 () Bool
    false)
  (define-fun N1_C1_E_m4r3c0_m4r3c1 () Bool
    false)
  (define-fun N1_C1_E_m4r3c1_m4r3c2 () Bool
    false)
  (define-fun N1_C1_E_m4r3c2_m4r3c3 () Bool
    false)
  (define-fun N1_C1_E_m4r3c3_m4r3c4 () Bool
    false)
  (define-fun N1_C1_E_m4r3c4_m4r3c5 () Bool
    false)
  (define-fun N1_C1_E_m4r3c5_m4r3c6 () Bool
    false)
  (define-fun M_m1r0c0_pinMM1_1 () Bool
    false)
  (define-fun M_m1r0c4_pinMM1_1 () Bool
    false)
  (define-fun M_m1r0c6_pinMM1_1 () Bool
    false)
  (define-fun M_m1r1c0_pinMM1_1 () Bool
    false)
  (define-fun M_m1r1c4_pinMM1_1 () Bool
    false)
  (define-fun M_m1r1c6_pinMM1_1 () Bool
    false)
  (define-fun M_m1r2c0_pinMM1_1 () Bool
    false)
  (define-fun M_m1r2c4_pinMM1_1 () Bool
    false)
  (define-fun M_m1r2c6_pinMM1_1 () Bool
    false)
  (define-fun M_m1r3c0_pinMM1_1 () Bool
    false)
  (define-fun M_m1r3c4_pinMM1_1 () Bool
    true)
  (define-fun M_m1r3c6_pinMM1_1 () Bool
    false)
  (define-fun M_m1r0c0_pinMM0_1 () Bool
    false)
  (define-fun M_m1r0c4_pinMM0_1 () Bool
    false)
  (define-fun M_m1r0c6_pinMM0_1 () Bool
    false)
  (define-fun M_m1r1c0_pinMM0_1 () Bool
    false)
  (define-fun M_m1r1c6_pinMM0_1 () Bool
    false)
  (define-fun M_m1r2c0_pinMM0_1 () Bool
    false)
  (define-fun M_m1r2c6_pinMM0_1 () Bool
    false)
  (define-fun M_m1r3c0_pinMM0_1 () Bool
    false)
  (define-fun M_m1r3c4_pinMM0_1 () Bool
    false)
  (define-fun M_m1r3c6_pinMM0_1 () Bool
    false)
  (define-fun N1_C1_E_m1r0c2_m1r1c2 () Bool
    false)
  (define-fun N1_C1_E_m1r1c2_m1r2c2 () Bool
    false)
  (define-fun N1_C1_E_m1r2c2_m1r3c2 () Bool
    false)
  (define-fun N1_C1_E_m1r3c2_pinMM1_1 () Bool
    false)
  (define-fun N1_C1_E_m1r0c2_pinMM0_1 () Bool
    false)
  (define-fun M_m1r0c2_pinMM1_1 () Bool
    false)
  (define-fun M_m1r1c2_pinMM1_1 () Bool
    false)
  (define-fun M_m1r2c2_pinMM1_1 () Bool
    false)
  (define-fun M_m1r3c2_pinMM1_1 () Bool
    false)
  (define-fun M_m1r0c2_pinMM0_1 () Bool
    false)
  (define-fun M_m1r3c2_pinMM0_1 () Bool
    true)
  (define-fun N1_C1_E_m1r3c4_pinMM1_1 () Bool
    true)
  (define-fun N1_C1_E_m1r0c4_pinMM0_1 () Bool
    false)
  (define-fun N2_C1_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N2_C1_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N2_C1_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N2_C1_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N2_C1_E_m1r0c2_m1r1c2 () Bool
    false)
  (define-fun N2_C1_E_m1r0c2_m2r0c2 () Bool
    false)
  (define-fun N2_C1_E_m1r0c3_m2r0c3 () Bool
    false)
  (define-fun N2_C1_E_m1r0c4_m1r1c4 () Bool
    false)
  (define-fun N2_C1_E_m1r0c4_m2r0c4 () Bool
    false)
  (define-fun N2_C1_E_m1r0c5_m1r1c5 () Bool
    false)
  (define-fun N2_C1_E_m1r0c5_m2r0c5 () Bool
    false)
  (define-fun N2_C1_E_m1r0c6_m1r1c6 () Bool
    false)
  (define-fun N2_C1_E_m1r0c6_m2r0c6 () Bool
    false)
  (define-fun N2_C1_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N2_C1_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N2_C1_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N2_C1_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N2_C1_E_m1r1c2_m1r2c2 () Bool
    false)
  (define-fun N2_C1_E_m1r1c2_m2r1c2 () Bool
    false)
  (define-fun N2_C1_E_m1r1c3_m2r1c3 () Bool
    false)
  (define-fun N2_C1_E_m1r1c4_m1r2c4 () Bool
    false)
  (define-fun N2_C1_E_m1r1c4_m2r1c4 () Bool
    false)
  (define-fun N2_C1_E_m1r1c5_m1r2c5 () Bool
    false)
  (define-fun N2_C1_E_m1r1c5_m2r1c5 () Bool
    false)
  (define-fun N2_C1_E_m1r1c6_m1r2c6 () Bool
    false)
  (define-fun N2_C1_E_m1r1c6_m2r1c6 () Bool
    false)
  (define-fun N2_C1_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N2_C1_E_m1r2c0_m2r2c0 () Bool
    false)
  (define-fun N2_C1_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N2_C1_E_m1r2c1_m2r2c1 () Bool
    false)
  (define-fun N2_C1_E_m1r2c2_m1r3c2 () Bool
    false)
  (define-fun N2_C1_E_m1r2c2_m2r2c2 () Bool
    false)
  (define-fun N2_C1_E_m1r2c3_m2r2c3 () Bool
    false)
  (define-fun N2_C1_E_m1r2c4_m1r3c4 () Bool
    false)
  (define-fun N2_C1_E_m1r2c4_m2r2c4 () Bool
    false)
  (define-fun N2_C1_E_m1r2c5_m1r3c5 () Bool
    false)
  (define-fun N2_C1_E_m1r2c5_m2r2c5 () Bool
    false)
  (define-fun N2_C1_E_m1r2c6_m1r3c6 () Bool
    false)
  (define-fun N2_C1_E_m1r2c6_m2r2c6 () Bool
    false)
  (define-fun N2_C1_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N2_C1_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N2_C1_E_m1r3c2_m2r3c2 () Bool
    false)
  (define-fun N2_C1_E_m1r3c3_m2r3c3 () Bool
    false)
  (define-fun N2_C1_E_m1r3c4_m2r3c4 () Bool
    false)
  (define-fun N2_C1_E_m1r3c5_m2r3c5 () Bool
    false)
  (define-fun N2_C1_E_m1r3c6_m2r3c6 () Bool
    false)
  (define-fun N2_C1_E_m2r0c0_m2r0c1 () Bool
    false)
  (define-fun N2_C1_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N2_C1_E_m2r0c1_m2r0c2 () Bool
    false)
  (define-fun N2_C1_E_m2r0c2_m2r0c3 () Bool
    false)
  (define-fun N2_C1_E_m2r0c2_m3r0c2 () Bool
    false)
  (define-fun N2_C1_E_m2r0c3_m2r0c4 () Bool
    false)
  (define-fun N2_C1_E_m2r0c4_m2r0c5 () Bool
    false)
  (define-fun N2_C1_E_m2r0c4_m3r0c4 () Bool
    false)
  (define-fun N2_C1_E_m2r0c5_m2r0c6 () Bool
    false)
  (define-fun N2_C1_E_m2r0c6_m3r0c6 () Bool
    false)
  (define-fun N2_C1_E_m2r1c0_m2r1c1 () Bool
    false)
  (define-fun N2_C1_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N2_C1_E_m2r1c1_m2r1c2 () Bool
    false)
  (define-fun N2_C1_E_m2r1c2_m2r1c3 () Bool
    false)
  (define-fun N2_C1_E_m2r1c2_m3r1c2 () Bool
    false)
  (define-fun N2_C1_E_m2r1c3_m2r1c4 () Bool
    false)
  (define-fun N2_C1_E_m2r1c4_m2r1c5 () Bool
    false)
  (define-fun N2_C1_E_m2r1c4_m3r1c4 () Bool
    false)
  (define-fun N2_C1_E_m2r1c5_m2r1c6 () Bool
    false)
  (define-fun N2_C1_E_m2r1c6_m3r1c6 () Bool
    false)
  (define-fun N2_C1_E_m2r2c0_m2r2c1 () Bool
    false)
  (define-fun N2_C1_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N2_C1_E_m2r2c1_m2r2c2 () Bool
    false)
  (define-fun N2_C1_E_m2r2c2_m2r2c3 () Bool
    false)
  (define-fun N2_C1_E_m2r2c2_m3r2c2 () Bool
    false)
  (define-fun N2_C1_E_m2r2c3_m2r2c4 () Bool
    false)
  (define-fun N2_C1_E_m2r2c4_m2r2c5 () Bool
    false)
  (define-fun N2_C1_E_m2r2c4_m3r2c4 () Bool
    false)
  (define-fun N2_C1_E_m2r2c5_m2r2c6 () Bool
    false)
  (define-fun N2_C1_E_m2r2c6_m3r2c6 () Bool
    false)
  (define-fun N2_C1_E_m2r3c0_m2r3c1 () Bool
    false)
  (define-fun N2_C1_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N2_C1_E_m2r3c1_m2r3c2 () Bool
    false)
  (define-fun N2_C1_E_m2r3c2_m2r3c3 () Bool
    false)
  (define-fun N2_C1_E_m2r3c2_m3r3c2 () Bool
    false)
  (define-fun N2_C1_E_m2r3c3_m2r3c4 () Bool
    false)
  (define-fun N2_C1_E_m2r3c4_m2r3c5 () Bool
    false)
  (define-fun N2_C1_E_m2r3c4_m3r3c4 () Bool
    false)
  (define-fun N2_C1_E_m2r3c5_m2r3c6 () Bool
    false)
  (define-fun N2_C1_E_m2r3c6_m3r3c6 () Bool
    false)
  (define-fun N2_C1_E_m3r0c0_m3r1c0 () Bool
    false)
  (define-fun N2_C1_E_m3r0c0_m4r0c0 () Bool
    false)
  (define-fun N2_C1_E_m3r0c2_m3r1c2 () Bool
    false)
  (define-fun N2_C1_E_m3r0c2_m4r0c2 () Bool
    false)
  (define-fun N2_C1_E_m3r0c4_m3r1c4 () Bool
    false)
  (define-fun N2_C1_E_m3r0c4_m4r0c4 () Bool
    false)
  (define-fun N2_C1_E_m3r0c6_m3r1c6 () Bool
    false)
  (define-fun N2_C1_E_m3r0c6_m4r0c6 () Bool
    false)
  (define-fun N2_C1_E_m3r1c0_m3r2c0 () Bool
    false)
  (define-fun N2_C1_E_m3r1c0_m4r1c0 () Bool
    false)
  (define-fun N2_C1_E_m3r1c2_m3r2c2 () Bool
    false)
  (define-fun N2_C1_E_m3r1c2_m4r1c2 () Bool
    false)
  (define-fun N2_C1_E_m3r1c4_m3r2c4 () Bool
    false)
  (define-fun N2_C1_E_m3r1c4_m4r1c4 () Bool
    false)
  (define-fun N2_C1_E_m3r1c6_m3r2c6 () Bool
    false)
  (define-fun N2_C1_E_m3r1c6_m4r1c6 () Bool
    false)
  (define-fun N2_C1_E_m3r2c0_m3r3c0 () Bool
    false)
  (define-fun N2_C1_E_m3r2c0_m4r2c0 () Bool
    false)
  (define-fun N2_C1_E_m3r2c2_m3r3c2 () Bool
    false)
  (define-fun N2_C1_E_m3r2c2_m4r2c2 () Bool
    false)
  (define-fun N2_C1_E_m3r2c4_m3r3c4 () Bool
    false)
  (define-fun N2_C1_E_m3r2c4_m4r2c4 () Bool
    false)
  (define-fun N2_C1_E_m3r2c6_m3r3c6 () Bool
    false)
  (define-fun N2_C1_E_m3r2c6_m4r2c6 () Bool
    false)
  (define-fun N2_C1_E_m3r3c0_m4r3c0 () Bool
    false)
  (define-fun N2_C1_E_m3r3c2_m4r3c2 () Bool
    false)
  (define-fun N2_C1_E_m3r3c4_m4r3c4 () Bool
    false)
  (define-fun N2_C1_E_m3r3c6_m4r3c6 () Bool
    false)
  (define-fun N2_C1_E_m4r0c0_m4r0c1 () Bool
    false)
  (define-fun N2_C1_E_m4r0c1_m4r0c2 () Bool
    false)
  (define-fun N2_C1_E_m4r0c2_m4r0c3 () Bool
    false)
  (define-fun N2_C1_E_m4r0c3_m4r0c4 () Bool
    false)
  (define-fun N2_C1_E_m4r0c4_m4r0c5 () Bool
    false)
  (define-fun N2_C1_E_m4r0c5_m4r0c6 () Bool
    false)
  (define-fun N2_C1_E_m4r1c0_m4r1c1 () Bool
    false)
  (define-fun N2_C1_E_m4r1c1_m4r1c2 () Bool
    false)
  (define-fun N2_C1_E_m4r1c2_m4r1c3 () Bool
    false)
  (define-fun N2_C1_E_m4r1c3_m4r1c4 () Bool
    false)
  (define-fun N2_C1_E_m4r1c4_m4r1c5 () Bool
    false)
  (define-fun N2_C1_E_m4r1c5_m4r1c6 () Bool
    false)
  (define-fun N2_C1_E_m4r2c0_m4r2c1 () Bool
    false)
  (define-fun N2_C1_E_m4r2c1_m4r2c2 () Bool
    false)
  (define-fun N2_C1_E_m4r2c2_m4r2c3 () Bool
    false)
  (define-fun N2_C1_E_m4r2c3_m4r2c4 () Bool
    false)
  (define-fun N2_C1_E_m4r2c4_m4r2c5 () Bool
    false)
  (define-fun N2_C1_E_m4r2c5_m4r2c6 () Bool
    false)
  (define-fun N2_C1_E_m4r3c0_m4r3c1 () Bool
    false)
  (define-fun N2_C1_E_m4r3c1_m4r3c2 () Bool
    false)
  (define-fun N2_C1_E_m4r3c2_m4r3c3 () Bool
    false)
  (define-fun N2_C1_E_m4r3c3_m4r3c4 () Bool
    false)
  (define-fun N2_C1_E_m4r3c4_m4r3c5 () Bool
    false)
  (define-fun N2_C1_E_m4r3c5_m4r3c6 () Bool
    false)
  (define-fun M_m1r0c1_pinMM1_2 () Bool
    false)
  (define-fun M_m1r0c5_pinMM1_2 () Bool
    false)
  (define-fun M_m1r1c1_pinMM1_2 () Bool
    false)
  (define-fun M_m1r1c5_pinMM1_2 () Bool
    false)
  (define-fun M_m1r2c1_pinMM1_2 () Bool
    false)
  (define-fun M_m1r2c5_pinMM1_2 () Bool
    false)
  (define-fun M_m1r3c1_pinMM1_2 () Bool
    false)
  (define-fun M_m1r3c5_pinMM1_2 () Bool
    false)
  (define-fun M_m1r0c1_pinMM0_2 () Bool
    false)
  (define-fun M_m1r0c5_pinMM0_2 () Bool
    false)
  (define-fun M_m1r3c1_pinMM0_2 () Bool
    false)
  (define-fun M_m1r3c5_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r0c3_m1r1c3 () Bool
    true)
  (define-fun N2_C1_E_m1r1c3_m1r2c3 () Bool
    true)
  (define-fun N2_C1_E_m1r2c3_m1r3c3 () Bool
    true)
  (define-fun N2_C1_E_m1r3c3_pinMM1_2 () Bool
    true)
  (define-fun N2_C1_E_m1r0c3_pinMM0_2 () Bool
    true)
  (define-fun N1_E_m1r2c3_m1r3c3 () Bool
    false)
  (define-fun N2_E_m1r2c3_m1r3c3 () Bool
    true)
  (define-fun N1_E_m1r0c3_m1r1c3 () Bool
    false)
  (define-fun N2_E_m1r0c3_m1r1c3 () Bool
    true)
  (define-fun N1_E_m1r1c3_m1r2c3 () Bool
    false)
  (define-fun N2_E_m1r1c3_m1r2c3 () Bool
    true)
  (define-fun ff1 () Bool
    false)
  (define-fun ff0 () Bool
    true)
  (define-fun M_m1r0c3_pinMM1_2 () Bool
    false)
  (define-fun M_m1r1c3_pinMM1_2 () Bool
    false)
  (define-fun M_m1r2c3_pinMM1_2 () Bool
    false)
  (define-fun M_m1r3c3_pinMM1_2 () Bool
    true)
  (define-fun M_m1r0c3_pinMM0_2 () Bool
    true)
  (define-fun M_m1r3c3_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r0c5_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r3c5_pinMM1_2 () Bool
    false)
  (define-fun N1_E_m1r2c5_m1r3c5 () Bool
    false)
  (define-fun N2_E_m1r2c5_m1r3c5 () Bool
    true)
  (define-fun N1_E_m1r0c5_m1r1c5 () Bool
    true)
  (define-fun N2_E_m1r0c5_m1r1c5 () Bool
    false)
  (define-fun N1_E_m1r1c5_m1r2c5 () Bool
    false)
  (define-fun N2_E_m1r1c5_m1r2c5 () Bool
    false)
  (define-fun N1_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N2_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N1_E_m1r1c1_m1r2c1 () Bool
    true)
  (define-fun N2_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N1_E_m1r2c1_m1r3c1 () Bool
    true)
  (define-fun N2_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N2_C1_E_m1r3c1_pinMM1_2 () Bool
    false)
  (define-fun N2_C1_E_m1r0c1_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m2r2c3_m3r2c3 () Bool
    false)
  (define-fun N2_E_m2r2c5_m3r2c5 () Bool
    false)
  (define-fun x0 () (_ BitVec 7)
    #b0000011)
  (define-fun GB_V_m3r3c6 () Bool
    true)
  (define-fun C_VIA_WO_N1_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N1_C0_E_m1r0c2_pinMM0_1 () Bool
    false)
  (define-fun N1_C0_E_m1r3c2_pinMM0_1 () Bool
    true)
  (define-fun N1_C0_E_m1r0c4_pinMM0_1 () Bool
    false)
  (define-fun N1_C0_E_m1r3c4_pinMM0_1 () Bool
    false)
  (define-fun N1_C0_E_m1r0c6_pinMM0_1 () Bool
    false)
  (define-fun N1_C0_E_m1r1c6_pinMM0_1 () Bool
    false)
  (define-fun N1_C0_E_m1r2c6_pinMM0_1 () Bool
    false)
  (define-fun N1_C0_E_m1r3c6_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m2r1c3_m3r1c3 () Bool
    false)
  (define-fun N1_C1_E_m1r3c2_pinMM0_1 () Bool
    true)
  (define-fun N1_C1_E_m1r3c4_pinMM0_1 () Bool
    false)
  (define-fun N1_C1_E_m1r0c6_pinMM0_1 () Bool
    false)
  (define-fun N1_C1_E_m1r1c6_pinMM0_1 () Bool
    false)
  (define-fun N1_C1_E_m1r2c6_pinMM0_1 () Bool
    false)
  (define-fun N1_C1_E_m1r3c6_pinMM0_1 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r2c4_m3r2c4 () Bool
    false)
  (define-fun N1_C1_E_m1r0c2_pinMM1_1 () Bool
    false)
  (define-fun N1_C1_E_m1r1c2_pinMM1_1 () Bool
    false)
  (define-fun N1_C1_E_m1r2c2_pinMM1_1 () Bool
    false)
  (define-fun N1_E_m2r1c5_m3r1c5 () Bool
    false)
  (define-fun N1_C1_E_m1r0c4_pinMM1_1 () Bool
    false)
  (define-fun N1_C1_E_m1r1c4_pinMM1_1 () Bool
    false)
  (define-fun N1_C1_E_m1r2c4_pinMM1_1 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N1_C1_E_m1r0c6_pinMM1_1 () Bool
    false)
  (define-fun N1_C1_E_m1r1c6_pinMM1_1 () Bool
    false)
  (define-fun N1_C1_E_m1r2c6_pinMM1_1 () Bool
    false)
  (define-fun N1_C1_E_m1r3c6_pinMM1_1 () Bool
    false)
  (define-fun N1_E_m2r2c3_m3r2c3 () Bool
    false)
  (define-fun N2_C0_E_m1r0c1_pinMM0_2 () Bool
    false)
  (define-fun N2_C0_E_m1r3c1_pinMM0_2 () Bool
    false)
  (define-fun N2_C0_E_m1r0c3_pinMM0_2 () Bool
    true)
  (define-fun N2_C0_E_m1r3c3_pinMM0_2 () Bool
    false)
  (define-fun N2_C0_E_m1r0c5_pinMM0_2 () Bool
    false)
  (define-fun N2_C0_E_m1r3c5_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r3c1_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r3c3_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r3c5_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r0c1_pinMM1_2 () Bool
    false)
  (define-fun N2_C1_E_m1r1c1_pinMM1_2 () Bool
    false)
  (define-fun N2_C1_E_m1r2c1_pinMM1_2 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r2c6_m3r2c6 () Bool
    true)
  (define-fun N2_C1_E_m1r0c3_pinMM1_2 () Bool
    false)
  (define-fun N2_C1_E_m1r1c3_pinMM1_2 () Bool
    false)
  (define-fun N2_C1_E_m1r2c3_pinMM1_2 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N2_C1_E_m1r0c5_pinMM1_2 () Bool
    false)
  (define-fun N2_C1_E_m1r1c5_pinMM1_2 () Bool
    false)
  (define-fun N2_C1_E_m1r2c5_pinMM1_2 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r0c2_m3r0c2 () Bool
    false)
  (define-fun N1_C0_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N1_C0_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N1_C0_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N1_C0_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N1_C0_E_m1r0c2_m1r1c2 () Bool
    false)
  (define-fun N1_C0_E_m1r0c2_m2r0c2 () Bool
    false)
  (define-fun N1_C0_E_m1r0c3_m1r1c3 () Bool
    false)
  (define-fun N1_C0_E_m1r0c3_m2r0c3 () Bool
    false)
  (define-fun N1_C0_E_m1r0c4_m1r1c4 () Bool
    false)
  (define-fun N1_C0_E_m1r0c4_m2r0c4 () Bool
    false)
  (define-fun N1_C0_E_m1r0c5_m1r1c5 () Bool
    false)
  (define-fun N1_C0_E_m1r0c5_m2r0c5 () Bool
    false)
  (define-fun N1_C0_E_m1r0c6_m1r1c6 () Bool
    false)
  (define-fun N1_C0_E_m1r0c6_m2r0c6 () Bool
    false)
  (define-fun N1_C0_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N1_C0_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N1_C0_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N1_C0_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N1_C0_E_m1r1c2_m1r2c2 () Bool
    false)
  (define-fun N1_C0_E_m1r1c2_m2r1c2 () Bool
    false)
  (define-fun N1_C0_E_m1r1c3_m1r2c3 () Bool
    false)
  (define-fun N1_C0_E_m1r1c3_m2r1c3 () Bool
    false)
  (define-fun N1_C0_E_m1r1c4_m1r2c4 () Bool
    false)
  (define-fun N1_C0_E_m1r1c4_m2r1c4 () Bool
    false)
  (define-fun N1_C0_E_m1r1c5_m1r2c5 () Bool
    false)
  (define-fun N1_C0_E_m1r1c5_m2r1c5 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r3c6_m3r3c6 () Bool
    false)
  (define-fun N1_C0_E_m1r1c6_m1r2c6 () Bool
    false)
  (define-fun N1_C0_E_m1r1c6_m2r1c6 () Bool
    false)
  (define-fun N1_C0_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N1_C0_E_m1r2c0_m2r2c0 () Bool
    false)
  (define-fun N1_C0_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N1_C0_E_m1r2c1_m2r2c1 () Bool
    false)
  (define-fun N1_C0_E_m1r2c2_m1r3c2 () Bool
    false)
  (define-fun N1_C0_E_m1r2c2_m2r2c2 () Bool
    false)
  (define-fun N1_C0_E_m1r2c3_m1r3c3 () Bool
    false)
  (define-fun N1_C0_E_m1r2c3_m2r2c3 () Bool
    false)
  (define-fun N1_C0_E_m1r2c4_m1r3c4 () Bool
    false)
  (define-fun N1_C0_E_m1r2c4_m2r2c4 () Bool
    false)
  (define-fun N1_C0_E_m1r2c5_m1r3c5 () Bool
    false)
  (define-fun N1_C0_E_m1r2c5_m2r2c5 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r3c2_m3r3c2 () Bool
    false)
  (define-fun N1_C0_E_m1r2c6_m1r3c6 () Bool
    false)
  (define-fun N1_C0_E_m1r2c6_m2r2c6 () Bool
    false)
  (define-fun N1_C0_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N1_C0_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N1_C0_E_m1r3c2_m2r3c2 () Bool
    true)
  (define-fun N1_C0_E_m1r3c3_m2r3c3 () Bool
    false)
  (define-fun N1_C0_E_m1r3c4_m2r3c4 () Bool
    false)
  (define-fun N1_C0_E_m1r3c5_m2r3c5 () Bool
    false)
  (define-fun N1_C0_E_m1r3c6_m2r3c6 () Bool
    false)
  (define-fun N1_C0_E_m2r0c0_m2r0c1 () Bool
    false)
  (define-fun N1_C0_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N1_C0_E_m2r0c1_m2r0c2 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r3c3_m3r3c3 () Bool
    false)
  (define-fun N1_C0_E_m2r0c2_m2r0c3 () Bool
    false)
  (define-fun N1_C0_E_m2r0c2_m3r0c2 () Bool
    false)
  (define-fun N1_C0_E_m2r0c3_m2r0c4 () Bool
    false)
  (define-fun N1_E_m2r3c3_m3r3c3 () Bool
    false)
  (define-fun N1_C0_E_m2r0c4_m2r0c5 () Bool
    false)
  (define-fun N1_C0_E_m2r0c4_m3r0c4 () Bool
    false)
  (define-fun N1_C0_E_m2r0c5_m2r0c6 () Bool
    false)
  (define-fun N1_C0_E_m2r0c6_m3r0c6 () Bool
    false)
  (define-fun N1_C0_E_m2r1c0_m2r1c1 () Bool
    false)
  (define-fun N1_C0_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N1_C0_E_m2r1c1_m2r1c2 () Bool
    false)
  (define-fun N1_E_m2r3c5_m3r3c5 () Bool
    false)
  (define-fun N1_C0_E_m2r1c2_m2r1c3 () Bool
    false)
  (define-fun N1_C0_E_m2r1c2_m3r1c2 () Bool
    false)
  (define-fun N1_C0_E_m2r1c3_m2r1c4 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r1c2_m4r1c2 () Bool
    false)
  (define-fun N1_C0_E_m2r1c4_m2r1c5 () Bool
    false)
  (define-fun N1_C0_E_m2r1c4_m3r1c4 () Bool
    false)
  (define-fun N1_C0_E_m2r1c5_m2r1c6 () Bool
    false)
  (define-fun N1_C0_E_m2r1c6_m3r1c6 () Bool
    false)
  (define-fun N1_C0_E_m2r2c0_m2r2c1 () Bool
    false)
  (define-fun N1_C0_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N1_C0_E_m2r2c1_m2r2c2 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r1c6_m4r1c6 () Bool
    false)
  (define-fun N1_C0_E_m2r2c2_m2r2c3 () Bool
    false)
  (define-fun N1_C0_E_m2r2c2_m3r2c2 () Bool
    false)
  (define-fun N1_C0_E_m2r2c3_m2r2c4 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r2c2_m4r2c2 () Bool
    false)
  (define-fun N1_C0_E_m2r2c4_m2r2c5 () Bool
    false)
  (define-fun N1_C0_E_m2r2c4_m3r2c4 () Bool
    false)
  (define-fun N1_C0_E_m2r2c5_m2r2c6 () Bool
    false)
  (define-fun N1_C0_E_m2r2c6_m3r2c6 () Bool
    false)
  (define-fun N1_C0_E_m2r3c0_m2r3c1 () Bool
    false)
  (define-fun N1_C0_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N1_C0_E_m2r3c1_m2r3c2 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r2c6_m4r2c6 () Bool
    false)
  (define-fun N1_C0_E_m2r3c2_m2r3c3 () Bool
    true)
  (define-fun N1_C0_E_m2r3c2_m3r3c2 () Bool
    false)
  (define-fun N1_C0_E_m2r3c3_m2r3c4 () Bool
    true)
  (define-fun C_VIA_WO_N1_E_m3r3c2_m4r3c2 () Bool
    false)
  (define-fun N1_C0_E_m2r3c4_m2r3c5 () Bool
    true)
  (define-fun N1_C0_E_m2r3c4_m3r3c4 () Bool
    false)
  (define-fun N1_C0_E_m2r3c5_m2r3c6 () Bool
    true)
  (define-fun N1_C0_E_m2r3c6_m3r3c6 () Bool
    true)
  (define-fun N1_C0_E_m3r0c0_m3r1c0 () Bool
    false)
  (define-fun N1_C0_E_m3r0c0_m4r0c0 () Bool
    false)
  (define-fun N1_C0_E_m3r0c2_m3r1c2 () Bool
    false)
  (define-fun N1_C0_E_m3r0c2_m4r0c2 () Bool
    false)
  (define-fun N1_C0_E_m3r0c4_m3r1c4 () Bool
    false)
  (define-fun N1_C0_E_m3r0c4_m4r0c4 () Bool
    false)
  (define-fun N1_C0_E_m3r0c6_m3r1c6 () Bool
    false)
  (define-fun N1_C0_E_m3r0c6_m4r0c6 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r1c2_m3r1c2 () Bool
    false)
  (define-fun N1_C0_E_m3r1c0_m3r2c0 () Bool
    false)
  (define-fun N1_C0_E_m3r1c0_m4r1c0 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r1c3_m3r1c3 () Bool
    false)
  (define-fun N1_C0_E_m3r1c2_m3r2c2 () Bool
    false)
  (define-fun N1_C0_E_m3r1c2_m4r1c2 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r1c6_m3r1c6 () Bool
    false)
  (define-fun N1_C0_E_m3r1c4_m3r2c4 () Bool
    false)
  (define-fun N1_C0_E_m3r1c4_m4r1c4 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r1c5_m3r1c5 () Bool
    false)
  (define-fun N1_C0_E_m3r1c6_m3r2c6 () Bool
    false)
  (define-fun N1_C0_E_m3r1c6_m4r1c6 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N1_C0_E_m3r2c0_m3r3c0 () Bool
    false)
  (define-fun N1_C0_E_m3r2c0_m4r2c0 () Bool
    false)
  (define-fun N2_E_m2r1c3_m3r1c3 () Bool
    false)
  (define-fun N1_C0_E_m3r2c2_m3r3c2 () Bool
    false)
  (define-fun N1_C0_E_m3r2c2_m4r2c2 () Bool
    false)
  (define-fun N2_E_m2r1c5_m3r1c5 () Bool
    false)
  (define-fun N1_C0_E_m3r2c4_m3r3c4 () Bool
    false)
  (define-fun N1_C0_E_m3r2c4_m4r2c4 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N1_C0_E_m3r2c6_m3r3c6 () Bool
    true)
  (define-fun N1_C0_E_m3r2c6_m4r2c6 () Bool
    false)
  (define-fun N1_C0_E_m3r3c0_m4r3c0 () Bool
    false)
  (define-fun N1_C0_E_m3r3c2_m4r3c2 () Bool
    false)
  (define-fun N1_C0_E_m3r3c4_m4r3c4 () Bool
    false)
  (define-fun N1_C0_E_m3r3c6_m4r3c6 () Bool
    false)
  (define-fun N1_C0_E_m4r0c0_m4r0c1 () Bool
    false)
  (define-fun N1_C0_E_m4r0c1_m4r0c2 () Bool
    false)
  (define-fun N1_C0_E_m4r0c2_m4r0c3 () Bool
    false)
  (define-fun N1_C0_E_m4r0c3_m4r0c4 () Bool
    false)
  (define-fun N1_C0_E_m4r0c4_m4r0c5 () Bool
    false)
  (define-fun N1_C0_E_m4r0c5_m4r0c6 () Bool
    false)
  (define-fun N1_C0_E_m4r1c0_m4r1c1 () Bool
    false)
  (define-fun N1_C0_E_m4r1c1_m4r1c2 () Bool
    false)
  (define-fun N1_C0_E_m4r1c2_m4r1c3 () Bool
    false)
  (define-fun N1_C0_E_m4r1c3_m4r1c4 () Bool
    false)
  (define-fun N1_C0_E_m4r1c4_m4r1c5 () Bool
    false)
  (define-fun N1_C0_E_m4r1c5_m4r1c6 () Bool
    false)
  (define-fun N1_C0_E_m4r2c0_m4r2c1 () Bool
    false)
  (define-fun N1_C0_E_m4r2c1_m4r2c2 () Bool
    false)
  (define-fun N1_C0_E_m4r2c2_m4r2c3 () Bool
    false)
  (define-fun N1_C0_E_m4r2c3_m4r2c4 () Bool
    false)
  (define-fun N1_C0_E_m4r2c4_m4r2c5 () Bool
    false)
  (define-fun N1_C0_E_m4r2c5_m4r2c6 () Bool
    false)
  (define-fun N1_C0_E_m4r3c0_m4r3c1 () Bool
    false)
  (define-fun N1_C0_E_m4r3c1_m4r3c2 () Bool
    false)
  (define-fun N1_C0_E_m4r3c2_m4r3c3 () Bool
    false)
  (define-fun N1_C0_E_m4r3c3_m4r3c4 () Bool
    false)
  (define-fun N1_C0_E_m4r3c4_m4r3c5 () Bool
    false)
  (define-fun N1_C0_E_m4r3c5_m4r3c6 () Bool
    false)
  (define-fun N2_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r3c4_m3r3c4 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r3c5_m3r3c5 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r1c0_m4r1c0 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r1c4_m4r1c4 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r2c2_m4r2c2 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r2c6_m4r2c6 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r3c2_m4r3c2 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun x1 () (_ BitVec 7)
    #b0000001)
  (define-fun COST_SIZE_P () (_ BitVec 7)
    #b0000000)
  (define-fun N1_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r2c3_m3r2c3 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r2c5_m3r2c5 () Bool
    false)
  (define-fun N1_E_m2r2c5_m3r2c5 () Bool
    false)
  (define-fun N2_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r0c3_m3r0c3 () Bool
    false)
  (define-fun N1_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r3c5_m3r3c5 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r1c4_m4r1c4 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r2c4_m4r2c4 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r3c4_m4r3c4 () Bool
    false)
  (define-fun N2_E_m2r0c3_m3r0c3 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r0c5_m3r0c5 () Bool
    false)
  (define-fun N2_E_m2r0c5_m3r0c5 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r2c6_m3r2c6 () Bool
    true)
  (define-fun C_VIA_WO_N2_E_m2r2c3_m3r2c3 () Bool
    false)
  (define-fun N2_C0_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N2_C0_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N2_C0_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N2_C0_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N2_C0_E_m1r0c2_m1r1c2 () Bool
    false)
  (define-fun N2_C0_E_m1r0c2_m2r0c2 () Bool
    false)
  (define-fun N2_C0_E_m1r0c3_m1r1c3 () Bool
    true)
  (define-fun N2_C0_E_m1r0c3_m2r0c3 () Bool
    false)
  (define-fun N2_C0_E_m1r0c4_m1r1c4 () Bool
    false)
  (define-fun N2_C0_E_m1r0c4_m2r0c4 () Bool
    false)
  (define-fun N2_C0_E_m1r0c5_m1r1c5 () Bool
    false)
  (define-fun N2_C0_E_m1r0c5_m2r0c5 () Bool
    false)
  (define-fun N2_C0_E_m1r0c6_m1r1c6 () Bool
    false)
  (define-fun N2_C0_E_m1r0c6_m2r0c6 () Bool
    false)
  (define-fun N2_C0_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N2_C0_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N2_C0_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N2_C0_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N2_C0_E_m1r1c2_m1r2c2 () Bool
    false)
  (define-fun N2_C0_E_m1r1c2_m2r1c2 () Bool
    false)
  (define-fun N2_C0_E_m1r1c3_m1r2c3 () Bool
    false)
  (define-fun N2_C0_E_m1r1c3_m2r1c3 () Bool
    true)
  (define-fun N2_C0_E_m1r1c4_m1r2c4 () Bool
    false)
  (define-fun N2_C0_E_m1r1c4_m2r1c4 () Bool
    false)
  (define-fun N2_C0_E_m1r1c5_m1r2c5 () Bool
    false)
  (define-fun N2_C0_E_m1r1c5_m2r1c5 () Bool
    false)
  (define-fun N2_C0_E_m1r1c6_m1r2c6 () Bool
    false)
  (define-fun N2_C0_E_m1r1c6_m2r1c6 () Bool
    false)
  (define-fun N2_C0_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N2_C0_E_m1r2c0_m2r2c0 () Bool
    false)
  (define-fun N2_C0_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N2_C0_E_m1r2c1_m2r2c1 () Bool
    false)
  (define-fun N2_C0_E_m1r2c2_m1r3c2 () Bool
    false)
  (define-fun N2_C0_E_m1r2c2_m2r2c2 () Bool
    false)
  (define-fun N2_C0_E_m1r2c3_m1r3c3 () Bool
    false)
  (define-fun N2_C0_E_m1r2c3_m2r2c3 () Bool
    false)
  (define-fun N2_C0_E_m1r2c4_m1r3c4 () Bool
    false)
  (define-fun N2_C0_E_m1r2c4_m2r2c4 () Bool
    false)
  (define-fun N2_C0_E_m1r2c5_m1r3c5 () Bool
    false)
  (define-fun N2_C0_E_m1r2c5_m2r2c5 () Bool
    false)
  (define-fun N2_C0_E_m1r2c6_m1r3c6 () Bool
    false)
  (define-fun N2_C0_E_m1r2c6_m2r2c6 () Bool
    false)
  (define-fun N2_C0_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N2_C0_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N2_C0_E_m1r3c2_m2r3c2 () Bool
    false)
  (define-fun N2_C0_E_m1r3c3_m2r3c3 () Bool
    false)
  (define-fun N2_C0_E_m1r3c4_m2r3c4 () Bool
    false)
  (define-fun N2_C0_E_m1r3c5_m2r3c5 () Bool
    false)
  (define-fun N2_C0_E_m1r3c6_m2r3c6 () Bool
    false)
  (define-fun N2_C0_E_m2r0c0_m2r0c1 () Bool
    false)
  (define-fun N2_C0_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N2_C0_E_m2r0c1_m2r0c2 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r2c5_m3r2c5 () Bool
    false)
  (define-fun N2_C0_E_m2r0c2_m2r0c3 () Bool
    false)
  (define-fun N2_C0_E_m2r0c2_m3r0c2 () Bool
    false)
  (define-fun N2_C0_E_m2r0c3_m2r0c4 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r3c2_m3r3c2 () Bool
    true)
  (define-fun N2_C0_E_m2r0c4_m2r0c5 () Bool
    false)
  (define-fun N2_C0_E_m2r0c4_m3r0c4 () Bool
    false)
  (define-fun N2_C0_E_m2r0c5_m2r0c6 () Bool
    false)
  (define-fun N2_C0_E_m2r0c6_m3r0c6 () Bool
    false)
  (define-fun N2_C0_E_m2r1c0_m2r1c1 () Bool
    false)
  (define-fun N2_C0_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N2_C0_E_m2r1c1_m2r1c2 () Bool
    false)
  (define-fun N2_E_m2r3c3_m3r3c3 () Bool
    false)
  (define-fun N2_C0_E_m2r1c2_m2r1c3 () Bool
    true)
  (define-fun N2_C0_E_m2r1c2_m3r1c2 () Bool
    true)
  (define-fun N2_C0_E_m2r1c3_m2r1c4 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r1c2_m4r1c2 () Bool
    false)
  (define-fun N2_C0_E_m2r1c4_m2r1c5 () Bool
    false)
  (define-fun N2_C0_E_m2r1c4_m3r1c4 () Bool
    false)
  (define-fun N2_C0_E_m2r1c5_m2r1c6 () Bool
    false)
  (define-fun N2_C0_E_m2r1c6_m3r1c6 () Bool
    false)
  (define-fun N2_C0_E_m2r2c0_m2r2c1 () Bool
    false)
  (define-fun N2_C0_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N2_C0_E_m2r2c1_m2r2c2 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r2c0_m4r2c0 () Bool
    false)
  (define-fun N2_C0_E_m2r2c2_m2r2c3 () Bool
    false)
  (define-fun N2_C0_E_m2r2c2_m3r2c2 () Bool
    false)
  (define-fun N2_C0_E_m2r2c3_m2r2c4 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r3c0_m4r3c0 () Bool
    false)
  (define-fun N2_C0_E_m2r2c4_m2r2c5 () Bool
    false)
  (define-fun N2_C0_E_m2r2c4_m3r2c4 () Bool
    false)
  (define-fun N2_C0_E_m2r2c5_m2r2c6 () Bool
    false)
  (define-fun N2_C0_E_m2r2c6_m3r2c6 () Bool
    false)
  (define-fun N2_C0_E_m2r3c0_m2r3c1 () Bool
    false)
  (define-fun N2_C0_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N2_C0_E_m2r3c1_m2r3c2 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r3c6_m4r3c6 () Bool
    false)
  (define-fun N2_C0_E_m2r3c2_m2r3c3 () Bool
    false)
  (define-fun N2_C0_E_m2r3c2_m3r3c2 () Bool
    false)
  (define-fun N2_C0_E_m2r3c3_m2r3c4 () Bool
    false)
  (define-fun COST_SIZE_N () (_ BitVec 7)
    #b1000000)
  (define-fun N2_C0_E_m2r3c4_m2r3c5 () Bool
    false)
  (define-fun N2_C0_E_m2r3c4_m3r3c4 () Bool
    false)
  (define-fun N2_C0_E_m2r3c5_m2r3c6 () Bool
    false)
  (define-fun N2_C0_E_m2r3c6_m3r3c6 () Bool
    false)
  (define-fun N2_C0_E_m3r0c0_m3r1c0 () Bool
    false)
  (define-fun N2_C0_E_m3r0c0_m4r0c0 () Bool
    false)
  (define-fun N2_C0_E_m3r0c2_m3r1c2 () Bool
    false)
  (define-fun N2_C0_E_m3r0c2_m4r0c2 () Bool
    false)
  (define-fun N2_C0_E_m3r0c4_m3r1c4 () Bool
    false)
  (define-fun N2_C0_E_m3r0c4_m4r0c4 () Bool
    false)
  (define-fun N2_C0_E_m3r0c6_m3r1c6 () Bool
    false)
  (define-fun N2_C0_E_m3r0c6_m4r0c6 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r1c6_m3r1c6 () Bool
    false)
  (define-fun N2_C0_E_m3r1c0_m3r2c0 () Bool
    false)
  (define-fun N2_C0_E_m3r1c0_m4r1c0 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N2_C0_E_m3r1c2_m3r2c2 () Bool
    true)
  (define-fun N2_C0_E_m3r1c2_m4r1c2 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r1c0_m4r1c0 () Bool
    false)
  (define-fun N2_C0_E_m3r1c4_m3r2c4 () Bool
    false)
  (define-fun N2_C0_E_m3r1c4_m4r1c4 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r3c6_m4r3c6 () Bool
    false)
  (define-fun N2_C0_E_m3r1c6_m3r2c6 () Bool
    false)
  (define-fun N2_C0_E_m3r1c6_m4r1c6 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r0c6_m3r0c6 () Bool
    false)
  (define-fun N2_C0_E_m3r2c0_m3r3c0 () Bool
    false)
  (define-fun N2_C0_E_m3r2c0_m4r2c0 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r2c4_m3r2c4 () Bool
    false)
  (define-fun N2_C0_E_m3r2c2_m3r3c2 () Bool
    false)
  (define-fun N2_C0_E_m3r2c2_m4r2c2 () Bool
    false)
  (define-fun N2_E_m2r3c5_m3r3c5 () Bool
    false)
  (define-fun N2_C0_E_m3r2c4_m3r3c4 () Bool
    false)
  (define-fun N2_C0_E_m3r2c4_m4r2c4 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r3c4_m4r3c4 () Bool
    false)
  (define-fun N2_C0_E_m3r2c6_m3r3c6 () Bool
    false)
  (define-fun N2_C0_E_m3r2c6_m4r2c6 () Bool
    false)
  (define-fun N2_C0_E_m3r3c0_m4r3c0 () Bool
    false)
  (define-fun N2_C0_E_m3r3c2_m4r3c2 () Bool
    false)
  (define-fun N2_C0_E_m3r3c4_m4r3c4 () Bool
    false)
  (define-fun N2_C0_E_m3r3c6_m4r3c6 () Bool
    false)
  (define-fun N2_C0_E_m4r0c0_m4r0c1 () Bool
    false)
  (define-fun N2_C0_E_m4r0c1_m4r0c2 () Bool
    false)
  (define-fun N2_C0_E_m4r0c2_m4r0c3 () Bool
    false)
  (define-fun N2_C0_E_m4r0c3_m4r0c4 () Bool
    false)
  (define-fun N2_C0_E_m4r0c4_m4r0c5 () Bool
    false)
  (define-fun N2_C0_E_m4r0c5_m4r0c6 () Bool
    false)
  (define-fun N2_C0_E_m4r1c0_m4r1c1 () Bool
    false)
  (define-fun N2_C0_E_m4r1c1_m4r1c2 () Bool
    false)
  (define-fun N2_C0_E_m4r1c2_m4r1c3 () Bool
    false)
  (define-fun N2_C0_E_m4r1c3_m4r1c4 () Bool
    false)
  (define-fun N2_C0_E_m4r1c4_m4r1c5 () Bool
    false)
  (define-fun N2_C0_E_m4r1c5_m4r1c6 () Bool
    false)
  (define-fun N2_C0_E_m4r2c0_m4r2c1 () Bool
    false)
  (define-fun N2_C0_E_m4r2c1_m4r2c2 () Bool
    false)
  (define-fun N2_C0_E_m4r2c2_m4r2c3 () Bool
    false)
  (define-fun N2_C0_E_m4r2c3_m4r2c4 () Bool
    false)
  (define-fun N2_C0_E_m4r2c4_m4r2c5 () Bool
    false)
  (define-fun N2_C0_E_m4r2c5_m4r2c6 () Bool
    false)
  (define-fun N2_C0_E_m4r3c0_m4r3c1 () Bool
    false)
  (define-fun N2_C0_E_m4r3c1_m4r3c2 () Bool
    false)
  (define-fun N2_C0_E_m4r3c2_m4r3c3 () Bool
    false)
  (define-fun N2_C0_E_m4r3c3_m4r3c4 () Bool
    false)
  (define-fun N2_C0_E_m4r3c4_m4r3c5 () Bool
    false)
  (define-fun N2_C0_E_m4r3c5_m4r3c6 () Bool
    false)
  (define-fun GB_V_m3r3c4 () Bool
    false)
  (define-fun N1_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r2c0_m4r2c0 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r0c4_m3r0c4 () Bool
    false)
  (define-fun N2_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r3c6_m3r3c6 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r1c6_m4r1c6 () Bool
    false)
  (define-fun N2_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m3r3c0_m4r3c0 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r2c2_m3r2c2 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m3r2c4_m4r2c4 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r3c4_m3r3c4 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r3c3_m3r3c3 () Bool
    false)
  (define-fun C_VIA_WO_N2_E_m2r1c4_m3r1c4 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r2c2_m3r2c2 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r0c3_m3r0c3 () Bool
    true)
  (define-fun C_VIA_WO_N1_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r1c3_m3r1c3 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r0c2_m3r0c2 () Bool
    false)
  (define-fun N1_E_m2r0c3_m3r0c3 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun N1_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r1c2_m3r1c2 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r0c4_m3r0c4 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r0c5_m3r0c5 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r1c4_m3r1c4 () Bool
    false)
  (define-fun N1_E_m2r0c5_m3r0c5 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r0c6_m3r0c6 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r1c5_m3r1c5 () Bool
    false)
  (define-fun N1_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N2_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N1_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N2_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N1_E_m1r0c2_m2r0c2 () Bool
    false)
  (define-fun N2_E_m1r0c2_m2r0c2 () Bool
    false)
  (define-fun N1_E_m1r0c3_m2r0c3 () Bool
    false)
  (define-fun N2_E_m1r0c3_m2r0c3 () Bool
    false)
  (define-fun N1_E_m1r0c4_m2r0c4 () Bool
    false)
  (define-fun N2_E_m1r0c4_m2r0c4 () Bool
    false)
  (define-fun N1_E_m1r0c5_m2r0c5 () Bool
    false)
  (define-fun N2_E_m1r0c5_m2r0c5 () Bool
    false)
  (define-fun N1_E_m1r0c6_m2r0c6 () Bool
    false)
  (define-fun N2_E_m1r0c6_m2r0c6 () Bool
    false)
  (define-fun N1_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N2_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N1_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N2_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N1_E_m1r1c2_m2r1c2 () Bool
    false)
  (define-fun N2_E_m1r1c2_m2r1c2 () Bool
    false)
  (define-fun N1_E_m1r1c3_m2r1c3 () Bool
    false)
  (define-fun N2_E_m1r1c3_m2r1c3 () Bool
    true)
  (define-fun N1_E_m1r1c4_m2r1c4 () Bool
    false)
  (define-fun N2_E_m1r1c4_m2r1c4 () Bool
    false)
  (define-fun N1_E_m1r1c5_m2r1c5 () Bool
    false)
  (define-fun N2_E_m1r1c5_m2r1c5 () Bool
    false)
  (define-fun N1_E_m1r1c6_m2r1c6 () Bool
    false)
  (define-fun N2_E_m1r1c6_m2r1c6 () Bool
    false)
  (define-fun N1_E_m1r2c0_m2r2c0 () Bool
    false)
  (define-fun N2_E_m1r2c0_m2r2c0 () Bool
    false)
  (define-fun N1_E_m1r2c1_m2r2c1 () Bool
    false)
  (define-fun N2_E_m1r2c1_m2r2c1 () Bool
    false)
  (define-fun N1_E_m1r2c2_m2r2c2 () Bool
    false)
  (define-fun N2_E_m1r2c2_m2r2c2 () Bool
    false)
  (define-fun N1_E_m1r2c3_m2r2c3 () Bool
    false)
  (define-fun N2_E_m1r2c3_m2r2c3 () Bool
    false)
  (define-fun N1_E_m1r2c4_m2r2c4 () Bool
    false)
  (define-fun N2_E_m1r2c4_m2r2c4 () Bool
    false)
  (define-fun N1_E_m1r2c5_m2r2c5 () Bool
    false)
  (define-fun N2_E_m1r2c5_m2r2c5 () Bool
    false)
  (define-fun N1_E_m1r2c6_m2r2c6 () Bool
    false)
  (define-fun N2_E_m1r2c6_m2r2c6 () Bool
    false)
  (define-fun N1_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N2_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N1_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N2_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N1_E_m1r3c2_m2r3c2 () Bool
    true)
  (define-fun N2_E_m1r3c2_m2r3c2 () Bool
    false)
  (define-fun N1_E_m1r3c3_m2r3c3 () Bool
    false)
  (define-fun N2_E_m1r3c3_m2r3c3 () Bool
    false)
  (define-fun N1_E_m1r3c4_m2r3c4 () Bool
    true)
  (define-fun N2_E_m1r3c4_m2r3c4 () Bool
    false)
  (define-fun N1_E_m1r3c5_m2r3c5 () Bool
    false)
  (define-fun N2_E_m1r3c5_m2r3c5 () Bool
    false)
  (define-fun N1_E_m1r3c6_m2r3c6 () Bool
    false)
  (define-fun N2_E_m1r3c6_m2r3c6 () Bool
    false)
  (define-fun N1_E_m2r0c0_m2r0c1 () Bool
    false)
  (define-fun N1_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N2_E_m2r0c0_m2r0c1 () Bool
    false)
  (define-fun N2_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N1_E_m2r0c1_m2r0c2 () Bool
    false)
  (define-fun N2_E_m2r0c1_m2r0c2 () Bool
    false)
  (define-fun N1_E_m2r0c2_m2r0c3 () Bool
    false)
  (define-fun N1_E_m2r0c2_m3r0c2 () Bool
    false)
  (define-fun N2_E_m2r0c2_m2r0c3 () Bool
    false)
  (define-fun N2_E_m2r0c2_m3r0c2 () Bool
    false)
  (define-fun N1_E_m2r0c3_m2r0c4 () Bool
    false)
  (define-fun N2_E_m2r0c3_m2r0c4 () Bool
    false)
  (define-fun N1_E_m2r0c4_m2r0c5 () Bool
    false)
  (define-fun N1_E_m2r0c4_m3r0c4 () Bool
    false)
  (define-fun N2_E_m2r0c4_m2r0c5 () Bool
    false)
  (define-fun N2_E_m2r0c4_m3r0c4 () Bool
    false)
  (define-fun N1_E_m2r0c5_m2r0c6 () Bool
    false)
  (define-fun N2_E_m2r0c5_m2r0c6 () Bool
    false)
  (define-fun N1_E_m2r0c6_m3r0c6 () Bool
    false)
  (define-fun N2_E_m2r0c6_m3r0c6 () Bool
    false)
  (define-fun N1_E_m2r1c0_m2r1c1 () Bool
    false)
  (define-fun N1_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N2_E_m2r1c0_m2r1c1 () Bool
    false)
  (define-fun N2_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N1_E_m2r1c1_m2r1c2 () Bool
    false)
  (define-fun N2_E_m2r1c1_m2r1c2 () Bool
    false)
  (define-fun N1_E_m2r1c2_m2r1c3 () Bool
    false)
  (define-fun N1_E_m2r1c2_m3r1c2 () Bool
    false)
  (define-fun N2_E_m2r1c2_m2r1c3 () Bool
    true)
  (define-fun N2_E_m2r1c2_m3r1c2 () Bool
    true)
  (define-fun N1_E_m2r1c3_m2r1c4 () Bool
    false)
  (define-fun N2_E_m2r1c3_m2r1c4 () Bool
    false)
  (define-fun N1_E_m2r1c4_m2r1c5 () Bool
    false)
  (define-fun N1_E_m2r1c4_m3r1c4 () Bool
    false)
  (define-fun N2_E_m2r1c4_m2r1c5 () Bool
    false)
  (define-fun N2_E_m2r1c4_m3r1c4 () Bool
    false)
  (define-fun N1_E_m2r1c5_m2r1c6 () Bool
    false)
  (define-fun N2_E_m2r1c5_m2r1c6 () Bool
    false)
  (define-fun N1_E_m2r1c6_m3r1c6 () Bool
    false)
  (define-fun N2_E_m2r1c6_m3r1c6 () Bool
    false)
  (define-fun N1_E_m2r2c0_m2r2c1 () Bool
    false)
  (define-fun N1_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N2_E_m2r2c0_m2r2c1 () Bool
    false)
  (define-fun N2_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N1_E_m2r2c1_m2r2c2 () Bool
    false)
  (define-fun N2_E_m2r2c1_m2r2c2 () Bool
    false)
  (define-fun N1_E_m2r2c2_m2r2c3 () Bool
    false)
  (define-fun N1_E_m2r2c2_m3r2c2 () Bool
    false)
  (define-fun N2_E_m2r2c2_m2r2c3 () Bool
    false)
  (define-fun N2_E_m2r2c2_m3r2c2 () Bool
    false)
  (define-fun N1_E_m2r2c3_m2r2c4 () Bool
    false)
  (define-fun N2_E_m2r2c3_m2r2c4 () Bool
    false)
  (define-fun N1_E_m2r2c4_m2r2c5 () Bool
    false)
  (define-fun N1_E_m2r2c4_m3r2c4 () Bool
    false)
  (define-fun N2_E_m2r2c4_m2r2c5 () Bool
    false)
  (define-fun N2_E_m2r2c4_m3r2c4 () Bool
    false)
  (define-fun N1_E_m2r2c5_m2r2c6 () Bool
    false)
  (define-fun N2_E_m2r2c5_m2r2c6 () Bool
    false)
  (define-fun N1_E_m2r2c6_m3r2c6 () Bool
    false)
  (define-fun N2_E_m2r2c6_m3r2c6 () Bool
    false)
  (define-fun N1_E_m2r3c0_m2r3c1 () Bool
    false)
  (define-fun N1_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N2_E_m2r3c0_m2r3c1 () Bool
    false)
  (define-fun N2_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N1_E_m2r3c1_m2r3c2 () Bool
    false)
  (define-fun N2_E_m2r3c1_m2r3c2 () Bool
    false)
  (define-fun N1_E_m2r3c2_m2r3c3 () Bool
    true)
  (define-fun N1_E_m2r3c2_m3r3c2 () Bool
    false)
  (define-fun N2_E_m2r3c2_m2r3c3 () Bool
    false)
  (define-fun N2_E_m2r3c2_m3r3c2 () Bool
    false)
  (define-fun N1_E_m2r3c3_m2r3c4 () Bool
    true)
  (define-fun N2_E_m2r3c3_m2r3c4 () Bool
    false)
  (define-fun N1_E_m2r3c4_m2r3c5 () Bool
    true)
  (define-fun N1_E_m2r3c4_m3r3c4 () Bool
    false)
  (define-fun N2_E_m2r3c4_m2r3c5 () Bool
    false)
  (define-fun N2_E_m2r3c4_m3r3c4 () Bool
    false)
  (define-fun N1_E_m2r3c5_m2r3c6 () Bool
    true)
  (define-fun N2_E_m2r3c5_m2r3c6 () Bool
    false)
  (define-fun N1_E_m2r3c6_m3r3c6 () Bool
    true)
  (define-fun N2_E_m2r3c6_m3r3c6 () Bool
    false)
  (define-fun N1_E_m3r0c0_m3r1c0 () Bool
    false)
  (define-fun N1_E_m3r0c0_m4r0c0 () Bool
    false)
  (define-fun N2_E_m3r0c0_m3r1c0 () Bool
    false)
  (define-fun N2_E_m3r0c0_m4r0c0 () Bool
    false)
  (define-fun N1_E_m3r0c2_m3r1c2 () Bool
    false)
  (define-fun N1_E_m3r0c2_m4r0c2 () Bool
    false)
  (define-fun N2_E_m3r0c2_m3r1c2 () Bool
    false)
  (define-fun N2_E_m3r0c2_m4r0c2 () Bool
    false)
  (define-fun N1_E_m3r0c4_m3r1c4 () Bool
    false)
  (define-fun N1_E_m3r0c4_m4r0c4 () Bool
    false)
  (define-fun N2_E_m3r0c4_m3r1c4 () Bool
    false)
  (define-fun N2_E_m3r0c4_m4r0c4 () Bool
    false)
  (define-fun N1_E_m3r0c6_m3r1c6 () Bool
    false)
  (define-fun N1_E_m3r0c6_m4r0c6 () Bool
    false)
  (define-fun N2_E_m3r0c6_m3r1c6 () Bool
    false)
  (define-fun N2_E_m3r0c6_m4r0c6 () Bool
    false)
  (define-fun N1_E_m3r1c0_m3r2c0 () Bool
    false)
  (define-fun N1_E_m3r1c0_m4r1c0 () Bool
    false)
  (define-fun N1_E_m3r1c0_pinSON () Bool
    false)
  (define-fun N2_E_m3r1c0_m3r2c0 () Bool
    false)
  (define-fun N2_E_m3r1c0_m4r1c0 () Bool
    false)
  (define-fun N2_E_m3r1c0_pinSON () Bool
    false)
  (define-fun N1_E_m3r1c2_m3r2c2 () Bool
    false)
  (define-fun N1_E_m3r1c2_m4r1c2 () Bool
    false)
  (define-fun N1_E_m3r1c2_pinSON () Bool
    false)
  (define-fun N2_E_m3r1c2_m3r2c2 () Bool
    true)
  (define-fun N2_E_m3r1c2_m4r1c2 () Bool
    false)
  (define-fun N2_E_m3r1c2_pinSON () Bool
    false)
  (define-fun N1_E_m3r1c4_m3r2c4 () Bool
    false)
  (define-fun N1_E_m3r1c4_m4r1c4 () Bool
    false)
  (define-fun N1_E_m3r1c4_pinSON () Bool
    false)
  (define-fun N2_E_m3r1c4_m3r2c4 () Bool
    false)
  (define-fun N2_E_m3r1c4_m4r1c4 () Bool
    false)
  (define-fun N2_E_m3r1c4_pinSON () Bool
    false)
  (define-fun N1_E_m3r1c6_m3r2c6 () Bool
    true)
  (define-fun N1_E_m3r1c6_m4r1c6 () Bool
    false)
  (define-fun N1_E_m3r1c6_pinSON () Bool
    false)
  (define-fun N2_E_m3r1c6_m3r2c6 () Bool
    false)
  (define-fun N2_E_m3r1c6_m4r1c6 () Bool
    false)
  (define-fun N2_E_m3r1c6_pinSON () Bool
    false)
  (define-fun N1_E_m3r2c0_m3r3c0 () Bool
    false)
  (define-fun N1_E_m3r2c0_m4r2c0 () Bool
    false)
  (define-fun N1_E_m3r2c0_pinSON () Bool
    false)
  (define-fun N2_E_m3r2c0_m3r3c0 () Bool
    false)
  (define-fun N2_E_m3r2c0_m4r2c0 () Bool
    false)
  (define-fun N2_E_m3r2c0_pinSON () Bool
    false)
  (define-fun N1_E_m3r2c2_m3r3c2 () Bool
    false)
  (define-fun N1_E_m3r2c2_m4r2c2 () Bool
    false)
  (define-fun N1_E_m3r2c2_pinSON () Bool
    false)
  (define-fun N2_E_m3r2c2_m3r3c2 () Bool
    true)
  (define-fun N2_E_m3r2c2_m4r2c2 () Bool
    false)
  (define-fun N2_E_m3r2c2_pinSON () Bool
    true)
  (define-fun N1_E_m3r2c4_m3r3c4 () Bool
    false)
  (define-fun N1_E_m3r2c4_m4r2c4 () Bool
    false)
  (define-fun N1_E_m3r2c4_pinSON () Bool
    false)
  (define-fun N2_E_m3r2c4_m3r3c4 () Bool
    false)
  (define-fun N2_E_m3r2c4_m4r2c4 () Bool
    false)
  (define-fun N2_E_m3r2c4_pinSON () Bool
    false)
  (define-fun N1_E_m3r2c6_m3r3c6 () Bool
    true)
  (define-fun N1_E_m3r2c6_m4r2c6 () Bool
    false)
  (define-fun N1_E_m3r2c6_pinSON () Bool
    true)
  (define-fun N2_E_m3r2c6_m3r3c6 () Bool
    false)
  (define-fun N2_E_m3r2c6_m4r2c6 () Bool
    false)
  (define-fun N2_E_m3r2c6_pinSON () Bool
    false)
  (define-fun N1_E_m3r3c0_m4r3c0 () Bool
    false)
  (define-fun N2_E_m3r3c0_m4r3c0 () Bool
    false)
  (define-fun N1_E_m3r3c2_m4r3c2 () Bool
    false)
  (define-fun N2_E_m3r3c2_m4r3c2 () Bool
    false)
  (define-fun N1_E_m3r3c4_m4r3c4 () Bool
    false)
  (define-fun N2_E_m3r3c4_m4r3c4 () Bool
    false)
  (define-fun N1_E_m3r3c6_m4r3c6 () Bool
    false)
  (define-fun N2_E_m3r3c6_m4r3c6 () Bool
    false)
  (define-fun N1_E_m4r0c0_m4r0c1 () Bool
    false)
  (define-fun N2_E_m4r0c0_m4r0c1 () Bool
    false)
  (define-fun N1_E_m4r0c1_m4r0c2 () Bool
    false)
  (define-fun N2_E_m4r0c1_m4r0c2 () Bool
    false)
  (define-fun N1_E_m4r0c2_m4r0c3 () Bool
    false)
  (define-fun N2_E_m4r0c2_m4r0c3 () Bool
    false)
  (define-fun N1_E_m4r0c3_m4r0c4 () Bool
    false)
  (define-fun N2_E_m4r0c3_m4r0c4 () Bool
    false)
  (define-fun N1_E_m4r0c4_m4r0c5 () Bool
    false)
  (define-fun N2_E_m4r0c4_m4r0c5 () Bool
    false)
  (define-fun N1_E_m4r0c5_m4r0c6 () Bool
    false)
  (define-fun N2_E_m4r0c5_m4r0c6 () Bool
    false)
  (define-fun N1_E_m4r1c0_m4r1c1 () Bool
    false)
  (define-fun N2_E_m4r1c0_m4r1c1 () Bool
    false)
  (define-fun N1_E_m4r1c1_m4r1c2 () Bool
    false)
  (define-fun N2_E_m4r1c1_m4r1c2 () Bool
    false)
  (define-fun N1_E_m4r1c2_m4r1c3 () Bool
    false)
  (define-fun N2_E_m4r1c2_m4r1c3 () Bool
    false)
  (define-fun N1_E_m4r1c3_m4r1c4 () Bool
    false)
  (define-fun N2_E_m4r1c3_m4r1c4 () Bool
    false)
  (define-fun N1_E_m4r1c4_m4r1c5 () Bool
    false)
  (define-fun N2_E_m4r1c4_m4r1c5 () Bool
    false)
  (define-fun N1_E_m4r1c5_m4r1c6 () Bool
    false)
  (define-fun N2_E_m4r1c5_m4r1c6 () Bool
    false)
  (define-fun N1_E_m4r2c0_m4r2c1 () Bool
    false)
  (define-fun N2_E_m4r2c0_m4r2c1 () Bool
    false)
  (define-fun N1_E_m4r2c1_m4r2c2 () Bool
    false)
  (define-fun N2_E_m4r2c1_m4r2c2 () Bool
    false)
  (define-fun N1_E_m4r2c2_m4r2c3 () Bool
    false)
  (define-fun N2_E_m4r2c2_m4r2c3 () Bool
    false)
  (define-fun N1_E_m4r2c3_m4r2c4 () Bool
    false)
  (define-fun N2_E_m4r2c3_m4r2c4 () Bool
    false)
  (define-fun N1_E_m4r2c4_m4r2c5 () Bool
    false)
  (define-fun N2_E_m4r2c4_m4r2c5 () Bool
    false)
  (define-fun N1_E_m4r2c5_m4r2c6 () Bool
    false)
  (define-fun N2_E_m4r2c5_m4r2c6 () Bool
    false)
  (define-fun N1_E_m4r3c0_m4r3c1 () Bool
    false)
  (define-fun N2_E_m4r3c0_m4r3c1 () Bool
    false)
  (define-fun N1_E_m4r3c1_m4r3c2 () Bool
    false)
  (define-fun N2_E_m4r3c1_m4r3c2 () Bool
    false)
  (define-fun N1_E_m4r3c2_m4r3c3 () Bool
    false)
  (define-fun N2_E_m4r3c2_m4r3c3 () Bool
    false)
  (define-fun N1_E_m4r3c3_m4r3c4 () Bool
    false)
  (define-fun N2_E_m4r3c3_m4r3c4 () Bool
    false)
  (define-fun N1_E_m4r3c4_m4r3c5 () Bool
    false)
  (define-fun N2_E_m4r3c4_m4r3c5 () Bool
    false)
  (define-fun N1_E_m4r3c5_m4r3c6 () Bool
    false)
  (define-fun N2_E_m4r3c5_m4r3c6 () Bool
    false)
  (define-fun C_VIA_WO_N1_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun GL_V_m2r0c0 () Bool
    false)
  (define-fun GL_V_m2r0c1 () Bool
    false)
  (define-fun GL_V_m2r0c2 () Bool
    false)
  (define-fun GL_V_m2r0c3 () Bool
    false)
  (define-fun GL_V_m2r0c4 () Bool
    false)
  (define-fun GL_V_m2r0c5 () Bool
    false)
  (define-fun GL_V_m2r0c6 () Bool
    true)
  (define-fun GL_V_m2r1c0 () Bool
    false)
  (define-fun GL_V_m2r1c1 () Bool
    false)
  (define-fun GL_V_m2r1c2 () Bool
    true)
  (define-fun GL_V_m2r1c3 () Bool
    false)
  (define-fun GL_V_m2r1c4 () Bool
    false)
  (define-fun GL_V_m2r1c5 () Bool
    false)
  (define-fun GL_V_m2r1c6 () Bool
    false)
  (define-fun GL_V_m2r2c0 () Bool
    false)
  (define-fun GL_V_m2r2c1 () Bool
    false)
  (define-fun GL_V_m2r2c2 () Bool
    false)
  (define-fun GL_V_m2r2c3 () Bool
    false)
  (define-fun GL_V_m2r2c4 () Bool
    false)
  (define-fun GL_V_m2r2c5 () Bool
    false)
  (define-fun GL_V_m2r2c6 () Bool
    false)
  (define-fun GL_V_m2r3c0 () Bool
    false)
  (define-fun GL_V_m2r3c1 () Bool
    false)
  (define-fun GL_V_m2r3c2 () Bool
    true)
  (define-fun GL_V_m2r3c3 () Bool
    false)
  (define-fun GL_V_m2r3c4 () Bool
    false)
  (define-fun GL_V_m2r3c5 () Bool
    false)
  (define-fun GL_V_m2r3c6 () Bool
    false)
  (define-fun GL_V_m4r0c0 () Bool
    false)
  (define-fun GL_V_m4r0c1 () Bool
    false)
  (define-fun GL_V_m4r0c2 () Bool
    false)
  (define-fun GL_V_m4r0c3 () Bool
    false)
  (define-fun GL_V_m4r0c4 () Bool
    false)
  (define-fun GL_V_m4r0c5 () Bool
    false)
  (define-fun GL_V_m4r0c6 () Bool
    true)
  (define-fun GL_V_m4r1c0 () Bool
    false)
  (define-fun GL_V_m4r1c1 () Bool
    false)
  (define-fun GL_V_m4r1c2 () Bool
    false)
  (define-fun GL_V_m4r1c3 () Bool
    false)
  (define-fun GL_V_m4r1c4 () Bool
    false)
  (define-fun GL_V_m4r1c5 () Bool
    false)
  (define-fun GL_V_m4r1c6 () Bool
    true)
  (define-fun GL_V_m4r2c0 () Bool
    false)
  (define-fun GL_V_m4r2c1 () Bool
    false)
  (define-fun GL_V_m4r2c2 () Bool
    false)
  (define-fun GL_V_m4r2c3 () Bool
    false)
  (define-fun GL_V_m4r2c4 () Bool
    false)
  (define-fun GL_V_m4r2c5 () Bool
    false)
  (define-fun GL_V_m4r2c6 () Bool
    false)
  (define-fun GL_V_m4r3c0 () Bool
    false)
  (define-fun GL_V_m4r3c1 () Bool
    false)
  (define-fun GL_V_m4r3c2 () Bool
    false)
  (define-fun GL_V_m4r3c3 () Bool
    false)
  (define-fun GL_V_m4r3c4 () Bool
    false)
  (define-fun GL_V_m4r3c5 () Bool
    false)
  (define-fun GL_V_m4r3c6 () Bool
    false)
  (define-fun GR_V_m2r0c0 () Bool
    false)
  (define-fun GR_V_m2r0c1 () Bool
    false)
  (define-fun GR_V_m2r0c2 () Bool
    false)
  (define-fun GR_V_m2r0c3 () Bool
    false)
  (define-fun GR_V_m2r0c4 () Bool
    false)
  (define-fun GR_V_m2r0c5 () Bool
    false)
  (define-fun GR_V_m2r0c6 () Bool
    false)
  (define-fun GR_V_m2r1c0 () Bool
    false)
  (define-fun GR_V_m2r1c1 () Bool
    false)
  (define-fun GR_V_m2r1c2 () Bool
    false)
  (define-fun GR_V_m2r1c3 () Bool
    true)
  (define-fun GR_V_m2r1c4 () Bool
    false)
  (define-fun GR_V_m2r1c5 () Bool
    false)
  (define-fun GR_V_m2r1c6 () Bool
    false)
  (define-fun GR_V_m2r2c0 () Bool
    false)
  (define-fun GR_V_m2r2c1 () Bool
    false)
  (define-fun GR_V_m2r2c2 () Bool
    false)
  (define-fun GR_V_m2r2c3 () Bool
    false)
  (define-fun GR_V_m2r2c4 () Bool
    false)
  (define-fun GR_V_m2r2c5 () Bool
    false)
  (define-fun GR_V_m2r2c6 () Bool
    false)
  (define-fun GR_V_m2r3c0 () Bool
    true)
  (define-fun GR_V_m2r3c1 () Bool
    false)
  (define-fun GR_V_m2r3c2 () Bool
    false)
  (define-fun GR_V_m2r3c3 () Bool
    false)
  (define-fun GR_V_m2r3c4 () Bool
    false)
  (define-fun GR_V_m2r3c5 () Bool
    false)
  (define-fun GR_V_m2r3c6 () Bool
    true)
  (define-fun GR_V_m4r0c0 () Bool
    false)
  (define-fun GR_V_m4r0c1 () Bool
    false)
  (define-fun GR_V_m4r0c2 () Bool
    false)
  (define-fun GR_V_m4r0c3 () Bool
    false)
  (define-fun GR_V_m4r0c4 () Bool
    false)
  (define-fun GR_V_m4r0c5 () Bool
    false)
  (define-fun GR_V_m4r0c6 () Bool
    false)
  (define-fun GR_V_m4r1c0 () Bool
    true)
  (define-fun GR_V_m4r1c1 () Bool
    false)
  (define-fun GR_V_m4r1c2 () Bool
    false)
  (define-fun GR_V_m4r1c3 () Bool
    false)
  (define-fun GR_V_m4r1c4 () Bool
    false)
  (define-fun GR_V_m4r1c5 () Bool
    false)
  (define-fun GR_V_m4r1c6 () Bool
    false)
  (define-fun GR_V_m4r2c0 () Bool
    false)
  (define-fun GR_V_m4r2c1 () Bool
    false)
  (define-fun GR_V_m4r2c2 () Bool
    false)
  (define-fun GR_V_m4r2c3 () Bool
    false)
  (define-fun GR_V_m4r2c4 () Bool
    false)
  (define-fun GR_V_m4r2c5 () Bool
    false)
  (define-fun GR_V_m4r2c6 () Bool
    false)
  (define-fun GR_V_m4r3c0 () Bool
    true)
  (define-fun GR_V_m4r3c1 () Bool
    false)
  (define-fun GR_V_m4r3c2 () Bool
    false)
  (define-fun GR_V_m4r3c3 () Bool
    false)
  (define-fun GR_V_m4r3c4 () Bool
    false)
  (define-fun GR_V_m4r3c5 () Bool
    false)
  (define-fun GR_V_m4r3c6 () Bool
    false)
  (define-fun GF_V_m1r0c0 () Bool
    true)
  (define-fun GF_V_m1r0c2 () Bool
    false)
  (define-fun GF_V_m1r0c4 () Bool
    false)
  (define-fun GF_V_m1r0c6 () Bool
    false)
  (define-fun GF_V_m1r1c0 () Bool
    false)
  (define-fun GF_V_m1r1c2 () Bool
    false)
  (define-fun GF_V_m1r1c4 () Bool
    false)
  (define-fun GF_V_m1r1c6 () Bool
    false)
  (define-fun GF_V_m1r2c0 () Bool
    false)
  (define-fun GF_V_m1r2c2 () Bool
    false)
  (define-fun GF_V_m1r2c4 () Bool
    false)
  (define-fun GF_V_m1r2c6 () Bool
    false)
  (define-fun GF_V_m1r3c0 () Bool
    false)
  (define-fun GF_V_m1r3c2 () Bool
    false)
  (define-fun GF_V_m1r3c4 () Bool
    false)
  (define-fun GF_V_m1r3c6 () Bool
    false)
  (define-fun GF_V_m3r0c0 () Bool
    false)
  (define-fun GF_V_m3r0c2 () Bool
    false)
  (define-fun GF_V_m3r0c4 () Bool
    false)
  (define-fun GF_V_m3r0c6 () Bool
    false)
  (define-fun GF_V_m3r1c0 () Bool
    false)
  (define-fun GF_V_m3r1c2 () Bool
    true)
  (define-fun GF_V_m3r1c4 () Bool
    false)
  (define-fun GF_V_m3r1c6 () Bool
    true)
  (define-fun GF_V_m3r2c0 () Bool
    false)
  (define-fun GF_V_m3r2c2 () Bool
    false)
  (define-fun GF_V_m3r2c4 () Bool
    false)
  (define-fun GF_V_m3r2c6 () Bool
    false)
  (define-fun GF_V_m3r3c0 () Bool
    false)
  (define-fun GF_V_m3r3c2 () Bool
    false)
  (define-fun GF_V_m3r3c4 () Bool
    false)
  (define-fun GF_V_m3r3c6 () Bool
    false)
  (define-fun GB_V_m1r0c0 () Bool
    false)
  (define-fun GB_V_m1r0c2 () Bool
    false)
  (define-fun GB_V_m1r0c4 () Bool
    false)
  (define-fun GB_V_m1r0c6 () Bool
    false)
  (define-fun GB_V_m1r1c0 () Bool
    false)
  (define-fun GB_V_m1r1c2 () Bool
    false)
  (define-fun GB_V_m1r1c4 () Bool
    false)
  (define-fun GB_V_m1r1c6 () Bool
    false)
  (define-fun GB_V_m1r2c0 () Bool
    false)
  (define-fun GB_V_m1r2c2 () Bool
    false)
  (define-fun GB_V_m1r2c4 () Bool
    false)
  (define-fun GB_V_m1r2c6 () Bool
    false)
  (define-fun GB_V_m1r3c0 () Bool
    true)
  (define-fun GB_V_m1r3c2 () Bool
    false)
  (define-fun GB_V_m1r3c4 () Bool
    false)
  (define-fun GB_V_m1r3c6 () Bool
    false)
  (define-fun GB_V_m3r0c0 () Bool
    false)
  (define-fun GB_V_m3r0c2 () Bool
    false)
  (define-fun GB_V_m3r0c4 () Bool
    false)
  (define-fun GB_V_m3r0c6 () Bool
    false)
  (define-fun GB_V_m3r1c0 () Bool
    false)
  (define-fun GB_V_m3r1c2 () Bool
    false)
  (define-fun GB_V_m3r1c4 () Bool
    false)
  (define-fun GB_V_m3r1c6 () Bool
    false)
  (define-fun GB_V_m3r2c0 () Bool
    false)
  (define-fun GB_V_m3r2c2 () Bool
    false)
  (define-fun GB_V_m3r2c4 () Bool
    false)
  (define-fun GB_V_m3r2c6 () Bool
    false)
  (define-fun GB_V_m3r3c0 () Bool
    false)
  (define-fun GB_V_m3r3c2 () Bool
    true)
  (define-fun COST_SIZE () (_ BitVec 7)
    #b0000000)
  (define-fun N1_M2_TRACK () Bool
    false)
  (define-fun N1_M2_TRACK_3 () Bool
    false)
  (define-fun N1_M2_TRACK_2 () Bool
    false)
  (define-fun N1_M2_TRACK_1 () Bool
    false)
  (define-fun N1_M2_TRACK_0 () Bool
    false)
  (define-fun N2_M2_TRACK () Bool
    false)
  (define-fun N2_M2_TRACK_3 () Bool
    false)
  (define-fun N2_M2_TRACK_2 () Bool
    false)
  (define-fun N2_M2_TRACK_1 () Bool
    false)
  (define-fun N2_M2_TRACK_0 () Bool
    false)
  (define-fun M2_TRACK_3 () Bool
    false)
  (define-fun M2_TRACK_2 () Bool
    false)
  (define-fun M2_TRACK_1 () Bool
    false)
  (define-fun M2_TRACK_0 () Bool
    false)
  (define-fun M_m1r1c4_pinMM0_1 () Bool
    false)
  (define-fun M_m1r2c3_pinMM0_2 () Bool
    false)
  (define-fun M_m1r1c2_pinMM0_1 () Bool
    false)
  (define-fun M_m1r2c4_pinMM0_1 () Bool
    false)
  (define-fun M_m1r1c3_pinMM0_2 () Bool
    false)
  (define-fun M_m1r2c2_pinMM0_1 () Bool
    false)
  (define-fun M_m1r1c1_pinMM0_2 () Bool
    false)
  (define-fun M_m1r2c1_pinMM0_2 () Bool
    false)
  (define-fun M_m1r1c5_pinMM0_2 () Bool
    false)
  (define-fun M_m1r2c5_pinMM0_2 () Bool
    false)
  (define-fun M_m3r2c6_pinSON () Bool
    true)
  (define-fun M_m3r2c4_pinSON () Bool
    false)
  (define-fun M_m3r2c2_pinSON () Bool
    true)
  (define-fun M_m3r2c0_pinSON () Bool
    false)
  (define-fun M_m3r1c6_pinSON () Bool
    false)
  (define-fun M_m3r1c4_pinSON () Bool
    false)
  (define-fun M_m3r1c2_pinSON () Bool
    false)
  (define-fun M_m3r1c0_pinSON () Bool
    false)
  (define-fun N2_E_m1r2c5_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m1r2c3_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m1r2c1_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m1r1c5_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m1r1c3_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m1r1c1_pinMM0_2 () Bool
    false)
  (define-fun N1_E_m1r2c4_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r2c2_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r1c4_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r1c2_pinMM0_1 () Bool
    false)
  (define-fun M_m4r3c5_m4r3c6 () Bool
    false)
  (define-fun M_m4r3c4_m4r3c5 () Bool
    false)
  (define-fun M_m4r3c3_m4r3c4 () Bool
    false)
  (define-fun M_m4r3c2_m4r3c3 () Bool
    false)
  (define-fun M_m4r3c1_m4r3c2 () Bool
    false)
  (define-fun M_m4r3c0_m4r3c1 () Bool
    false)
  (define-fun M_m4r2c5_m4r2c6 () Bool
    false)
  (define-fun M_m4r2c4_m4r2c5 () Bool
    false)
  (define-fun M_m4r2c3_m4r2c4 () Bool
    false)
  (define-fun M_m4r2c2_m4r2c3 () Bool
    false)
  (define-fun M_m4r2c1_m4r2c2 () Bool
    false)
  (define-fun M_m4r2c0_m4r2c1 () Bool
    false)
  (define-fun M_m4r1c5_m4r1c6 () Bool
    false)
  (define-fun M_m4r1c4_m4r1c5 () Bool
    false)
  (define-fun M_m4r1c3_m4r1c4 () Bool
    false)
  (define-fun M_m4r1c2_m4r1c3 () Bool
    false)
  (define-fun M_m4r1c1_m4r1c2 () Bool
    false)
  (define-fun M_m4r1c0_m4r1c1 () Bool
    false)
  (define-fun M_m4r0c5_m4r0c6 () Bool
    false)
  (define-fun M_m4r0c4_m4r0c5 () Bool
    false)
  (define-fun M_m4r0c3_m4r0c4 () Bool
    false)
  (define-fun M_m4r0c2_m4r0c3 () Bool
    false)
  (define-fun M_m4r0c1_m4r0c2 () Bool
    false)
  (define-fun M_m4r0c0_m4r0c1 () Bool
    false)
  (define-fun M_m3r3c6_m4r3c6 () Bool
    false)
  (define-fun M_m3r3c4_m4r3c4 () Bool
    false)
  (define-fun M_m3r3c2_m4r3c2 () Bool
    false)
  (define-fun M_m3r3c0_m4r3c0 () Bool
    false)
  (define-fun M_m3r2c6_m4r2c6 () Bool
    false)
  (define-fun M_m3r2c6_m3r3c6 () Bool
    true)
  (define-fun M_m3r2c4_m4r2c4 () Bool
    false)
  (define-fun M_m3r2c4_m3r3c4 () Bool
    false)
  (define-fun M_m3r2c2_m4r2c2 () Bool
    false)
  (define-fun M_m3r2c2_m3r3c2 () Bool
    true)
  (define-fun M_m3r2c0_m4r2c0 () Bool
    false)
  (define-fun M_m3r2c0_m3r3c0 () Bool
    false)
  (define-fun M_m3r1c6_m4r1c6 () Bool
    false)
  (define-fun M_m3r1c6_m3r2c6 () Bool
    true)
  (define-fun M_m3r1c4_m4r1c4 () Bool
    false)
  (define-fun M_m3r1c4_m3r2c4 () Bool
    false)
  (define-fun M_m3r1c2_m4r1c2 () Bool
    false)
  (define-fun M_m3r1c2_m3r2c2 () Bool
    true)
  (define-fun M_m3r1c0_m4r1c0 () Bool
    false)
  (define-fun M_m3r1c0_m3r2c0 () Bool
    false)
  (define-fun M_m3r0c6_m4r0c6 () Bool
    false)
  (define-fun M_m3r0c6_m3r1c6 () Bool
    false)
  (define-fun M_m3r0c4_m4r0c4 () Bool
    false)
  (define-fun M_m3r0c4_m3r1c4 () Bool
    false)
  (define-fun M_m3r0c2_m4r0c2 () Bool
    false)
  (define-fun M_m3r0c2_m3r1c2 () Bool
    false)
  (define-fun M_m3r0c0_m4r0c0 () Bool
    false)
  (define-fun M_m3r0c0_m3r1c0 () Bool
    false)
  (define-fun M_m2r3c6_m3r3c6 () Bool
    true)
  (define-fun M_m2r3c5_m2r3c6 () Bool
    true)
  (define-fun M_m2r3c4_m3r3c4 () Bool
    false)
  (define-fun M_m2r3c4_m2r3c5 () Bool
    true)
  (define-fun M_m2r3c3_m2r3c4 () Bool
    true)
  (define-fun M_m2r3c2_m3r3c2 () Bool
    false)
  (define-fun M_m2r3c2_m2r3c3 () Bool
    true)
  (define-fun M_m2r3c1_m2r3c2 () Bool
    false)
  (define-fun M_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun M_m2r3c0_m2r3c1 () Bool
    false)
  (define-fun M_m2r2c6_m3r2c6 () Bool
    false)
  (define-fun M_m2r2c5_m2r2c6 () Bool
    false)
  (define-fun M_m2r2c4_m3r2c4 () Bool
    false)
  (define-fun M_m2r2c4_m2r2c5 () Bool
    false)
  (define-fun M_m2r2c3_m2r2c4 () Bool
    false)
  (define-fun M_m2r2c2_m3r2c2 () Bool
    false)
  (define-fun M_m2r2c2_m2r2c3 () Bool
    false)
  (define-fun M_m2r2c1_m2r2c2 () Bool
    false)
  (define-fun M_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun M_m2r2c0_m2r2c1 () Bool
    false)
  (define-fun M_m2r1c6_m3r1c6 () Bool
    false)
  (define-fun M_m2r1c5_m2r1c6 () Bool
    false)
  (define-fun M_m2r1c4_m3r1c4 () Bool
    false)
  (define-fun M_m2r1c4_m2r1c5 () Bool
    false)
  (define-fun M_m2r1c3_m2r1c4 () Bool
    false)
  (define-fun M_m2r1c2_m3r1c2 () Bool
    true)
  (define-fun M_m2r1c2_m2r1c3 () Bool
    true)
  (define-fun M_m2r1c1_m2r1c2 () Bool
    false)
  (define-fun M_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun M_m2r1c0_m2r1c1 () Bool
    false)
  (define-fun M_m2r0c6_m3r0c6 () Bool
    false)
  (define-fun M_m2r0c5_m2r0c6 () Bool
    false)
  (define-fun M_m2r0c4_m3r0c4 () Bool
    false)
  (define-fun M_m2r0c4_m2r0c5 () Bool
    false)
  (define-fun M_m2r0c3_m2r0c4 () Bool
    false)
  (define-fun M_m2r0c2_m3r0c2 () Bool
    false)
  (define-fun M_m2r0c2_m2r0c3 () Bool
    false)
  (define-fun M_m2r0c1_m2r0c2 () Bool
    false)
  (define-fun M_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun M_m2r0c0_m2r0c1 () Bool
    false)
  (define-fun M_m1r3c6_m2r3c6 () Bool
    false)
  (define-fun M_m1r3c5_m2r3c5 () Bool
    false)
  (define-fun M_m1r3c4_m2r3c4 () Bool
    true)
  (define-fun M_m1r3c3_m2r3c3 () Bool
    false)
  (define-fun M_m1r3c2_m2r3c2 () Bool
    true)
  (define-fun M_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun M_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun M_m1r2c6_m2r2c6 () Bool
    false)
  (define-fun M_m1r2c6_m1r3c6 () Bool
    false)
  (define-fun M_m1r2c5_m2r2c5 () Bool
    false)
  (define-fun M_m1r2c5_m1r3c5 () Bool
    true)
  (define-fun M_m1r2c4_m2r2c4 () Bool
    false)
  (define-fun M_m1r2c4_m1r3c4 () Bool
    false)
  (define-fun M_m1r2c3_m2r2c3 () Bool
    false)
  (define-fun M_m1r2c3_m1r3c3 () Bool
    true)
  (define-fun M_m1r2c2_m2r2c2 () Bool
    false)
  (define-fun M_m1r2c2_m1r3c2 () Bool
    false)
  (define-fun M_m1r2c1_m2r2c1 () Bool
    false)
  (define-fun M_m1r2c1_m1r3c1 () Bool
    true)
  (define-fun M_m1r2c0_m2r2c0 () Bool
    false)
  (define-fun M_m1r2c0_m1r3c0 () Bool
    true)
  (define-fun M_m1r1c6_m2r1c6 () Bool
    false)
  (define-fun M_m1r1c6_m1r2c6 () Bool
    false)
  (define-fun M_m1r1c5_m2r1c5 () Bool
    false)
  (define-fun M_m1r1c5_m1r2c5 () Bool
    false)
  (define-fun M_m1r1c4_m2r1c4 () Bool
    false)
  (define-fun M_m1r1c4_m1r2c4 () Bool
    false)
  (define-fun M_m1r1c3_m2r1c3 () Bool
    true)
  (define-fun M_m1r1c3_m1r2c3 () Bool
    true)
  (define-fun M_m1r1c2_m2r1c2 () Bool
    false)
  (define-fun M_m1r1c2_m1r2c2 () Bool
    false)
  (define-fun M_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun M_m1r1c1_m1r2c1 () Bool
    true)
  (define-fun M_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun M_m1r1c0_m1r2c0 () Bool
    true)
  (define-fun M_m1r0c6_m2r0c6 () Bool
    false)
  (define-fun M_m1r0c6_m1r1c6 () Bool
    false)
  (define-fun M_m1r0c5_m2r0c5 () Bool
    false)
  (define-fun M_m1r0c5_m1r1c5 () Bool
    true)
  (define-fun M_m1r0c4_m2r0c4 () Bool
    false)
  (define-fun M_m1r0c4_m1r1c4 () Bool
    false)
  (define-fun M_m1r0c3_m2r0c3 () Bool
    false)
  (define-fun M_m1r0c3_m1r1c3 () Bool
    true)
  (define-fun M_m1r0c2_m2r0c2 () Bool
    false)
  (define-fun M_m1r0c2_m1r1c2 () Bool
    false)
  (define-fun M_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun M_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun M_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun M_m1r0c0_m1r1c0 () Bool
    true)
  (define-fun N2_C1_E_m1r2c5_pinMM0_2 () Bool
    false)
  (define-fun N2_C0_E_m1r2c5_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r2c3_pinMM0_2 () Bool
    false)
  (define-fun N2_C0_E_m1r2c3_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r2c1_pinMM0_2 () Bool
    false)
  (define-fun N2_C0_E_m1r2c1_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r1c5_pinMM0_2 () Bool
    false)
  (define-fun N2_C0_E_m1r1c5_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r1c3_pinMM0_2 () Bool
    false)
  (define-fun N2_C0_E_m1r1c3_pinMM0_2 () Bool
    false)
  (define-fun N2_C1_E_m1r1c1_pinMM0_2 () Bool
    false)
  (define-fun N2_C0_E_m1r1c1_pinMM0_2 () Bool
    false)
  (define-fun N1_C1_E_m1r2c4_pinMM0_1 () Bool
    false)
  (define-fun N1_C0_E_m1r2c4_pinMM0_1 () Bool
    false)
  (define-fun N1_C1_E_m1r2c2_pinMM0_1 () Bool
    false)
  (define-fun N1_C0_E_m1r2c2_pinMM0_1 () Bool
    false)
  (define-fun N1_C1_E_m1r1c4_pinMM0_1 () Bool
    false)
  (define-fun N1_C0_E_m1r1c4_pinMM0_1 () Bool
    false)
  (define-fun N1_C1_E_m1r1c2_pinMM0_1 () Bool
    false)
  (define-fun N1_C0_E_m1r1c2_pinMM0_1 () Bool
    false)
  (define-fun C_N2_m4r3c6 () Bool
    false)
  (define-fun C_N1_m4r3c6 () Bool
    false)
  (define-fun C_N2_m4r3c5 () Bool
    false)
  (define-fun C_N1_m4r3c5 () Bool
    false)
  (define-fun C_N2_m4r3c4 () Bool
    false)
  (define-fun C_N1_m4r3c4 () Bool
    false)
  (define-fun C_N2_m4r3c3 () Bool
    false)
  (define-fun C_N1_m4r3c3 () Bool
    false)
  (define-fun C_N2_m4r3c2 () Bool
    false)
  (define-fun C_N1_m4r3c2 () Bool
    false)
  (define-fun C_N2_m4r3c1 () Bool
    false)
  (define-fun C_N1_m4r3c1 () Bool
    false)
  (define-fun C_N2_m4r3c0 () Bool
    false)
  (define-fun C_N1_m4r3c0 () Bool
    false)
  (define-fun C_N2_m4r2c6 () Bool
    false)
  (define-fun C_N1_m4r2c6 () Bool
    false)
  (define-fun C_N2_m4r2c5 () Bool
    false)
  (define-fun C_N1_m4r2c5 () Bool
    false)
  (define-fun C_N2_m4r2c4 () Bool
    false)
  (define-fun C_N1_m4r2c4 () Bool
    false)
  (define-fun C_N2_m4r2c3 () Bool
    false)
  (define-fun C_N1_m4r2c3 () Bool
    false)
  (define-fun C_N2_m4r2c2 () Bool
    false)
  (define-fun C_N1_m4r2c2 () Bool
    false)
  (define-fun C_N2_m4r2c1 () Bool
    false)
  (define-fun C_N1_m4r2c1 () Bool
    false)
  (define-fun C_N2_m4r2c0 () Bool
    false)
  (define-fun C_N1_m4r2c0 () Bool
    false)
  (define-fun C_N2_m4r1c6 () Bool
    false)
  (define-fun C_N1_m4r1c6 () Bool
    false)
  (define-fun C_N2_m4r1c5 () Bool
    false)
  (define-fun C_N1_m4r1c5 () Bool
    false)
  (define-fun C_N2_m4r1c4 () Bool
    false)
  (define-fun C_N1_m4r1c4 () Bool
    false)
  (define-fun C_N2_m4r1c3 () Bool
    false)
  (define-fun C_N1_m4r1c3 () Bool
    false)
  (define-fun C_N2_m4r1c2 () Bool
    false)
  (define-fun C_N1_m4r1c2 () Bool
    false)
  (define-fun C_N2_m4r1c1 () Bool
    false)
  (define-fun C_N1_m4r1c1 () Bool
    false)
  (define-fun C_N2_m4r1c0 () Bool
    false)
  (define-fun C_N1_m4r1c0 () Bool
    false)
  (define-fun C_N2_m4r0c6 () Bool
    false)
  (define-fun C_N1_m4r0c6 () Bool
    false)
  (define-fun C_N2_m4r0c5 () Bool
    false)
  (define-fun C_N1_m4r0c5 () Bool
    false)
  (define-fun C_N2_m4r0c4 () Bool
    false)
  (define-fun C_N1_m4r0c4 () Bool
    false)
  (define-fun C_N2_m4r0c3 () Bool
    false)
  (define-fun C_N1_m4r0c3 () Bool
    false)
  (define-fun C_N2_m4r0c2 () Bool
    false)
  (define-fun C_N1_m4r0c2 () Bool
    false)
  (define-fun C_N2_m4r0c1 () Bool
    false)
  (define-fun C_N1_m4r0c1 () Bool
    false)
  (define-fun C_N2_m4r0c0 () Bool
    false)
  (define-fun C_N1_m4r0c0 () Bool
    false)
  (define-fun C_N2_m3r3c6 () Bool
    false)
  (define-fun C_N1_m3r3c6 () Bool
    true)
  (define-fun C_N2_m3r3c4 () Bool
    false)
  (define-fun C_N1_m3r3c4 () Bool
    false)
  (define-fun C_N2_m3r3c2 () Bool
    true)
  (define-fun C_N1_m3r3c2 () Bool
    false)
  (define-fun C_N2_m3r3c0 () Bool
    false)
  (define-fun C_N1_m3r3c0 () Bool
    false)
  (define-fun C_N2_m3r2c6 () Bool
    false)
  (define-fun C_N1_m3r2c6 () Bool
    true)
  (define-fun C_N2_m3r2c4 () Bool
    false)
  (define-fun C_N1_m3r2c4 () Bool
    false)
  (define-fun C_N2_m3r2c2 () Bool
    true)
  (define-fun C_N1_m3r2c2 () Bool
    false)
  (define-fun C_N2_m3r2c0 () Bool
    false)
  (define-fun C_N1_m3r2c0 () Bool
    false)
  (define-fun C_N2_m3r1c6 () Bool
    false)
  (define-fun C_N1_m3r1c6 () Bool
    true)
  (define-fun C_N2_m3r1c4 () Bool
    false)
  (define-fun C_N1_m3r1c4 () Bool
    false)
  (define-fun C_N2_m3r1c2 () Bool
    true)
  (define-fun C_N1_m3r1c2 () Bool
    false)
  (define-fun C_N2_m3r1c0 () Bool
    false)
  (define-fun C_N1_m3r1c0 () Bool
    false)
  (define-fun C_N2_m3r0c6 () Bool
    false)
  (define-fun C_N1_m3r0c6 () Bool
    false)
  (define-fun C_N2_m3r0c4 () Bool
    false)
  (define-fun C_N1_m3r0c4 () Bool
    false)
  (define-fun C_N2_m3r0c2 () Bool
    false)
  (define-fun C_N1_m3r0c2 () Bool
    false)
  (define-fun C_N2_m3r0c0 () Bool
    false)
  (define-fun C_N1_m3r0c0 () Bool
    false)
  (define-fun C_N2_m2r3c6 () Bool
    false)
  (define-fun C_N1_m2r3c6 () Bool
    true)
  (define-fun C_N2_m2r3c5 () Bool
    false)
  (define-fun C_N1_m2r3c5 () Bool
    true)
  (define-fun C_N2_m2r3c4 () Bool
    false)
  (define-fun C_N1_m2r3c4 () Bool
    true)
  (define-fun C_N2_m2r3c3 () Bool
    false)
  (define-fun C_N1_m2r3c3 () Bool
    true)
  (define-fun C_N2_m2r3c2 () Bool
    false)
  (define-fun C_N1_m2r3c2 () Bool
    true)
  (define-fun C_N2_m2r3c1 () Bool
    false)
  (define-fun C_N1_m2r3c1 () Bool
    false)
  (define-fun C_N2_m2r3c0 () Bool
    false)
  (define-fun C_N1_m2r3c0 () Bool
    false)
  (define-fun C_N2_m2r2c6 () Bool
    false)
  (define-fun C_N1_m2r2c6 () Bool
    false)
  (define-fun C_N2_m2r2c5 () Bool
    false)
  (define-fun C_N1_m2r2c5 () Bool
    false)
  (define-fun C_N2_m2r2c4 () Bool
    false)
  (define-fun C_N1_m2r2c4 () Bool
    false)
  (define-fun C_N2_m2r2c3 () Bool
    false)
  (define-fun C_N1_m2r2c3 () Bool
    false)
  (define-fun C_N2_m2r2c2 () Bool
    false)
  (define-fun C_N1_m2r2c2 () Bool
    false)
  (define-fun C_N2_m2r2c1 () Bool
    false)
  (define-fun C_N1_m2r2c1 () Bool
    false)
  (define-fun C_N2_m2r2c0 () Bool
    false)
  (define-fun C_N1_m2r2c0 () Bool
    false)
  (define-fun C_N2_m2r1c6 () Bool
    false)
  (define-fun C_N1_m2r1c6 () Bool
    false)
  (define-fun C_N2_m2r1c5 () Bool
    false)
  (define-fun C_N1_m2r1c5 () Bool
    false)
  (define-fun C_N2_m2r1c4 () Bool
    false)
  (define-fun C_N1_m2r1c4 () Bool
    false)
  (define-fun C_N2_m2r1c3 () Bool
    true)
  (define-fun C_N1_m2r1c3 () Bool
    false)
  (define-fun C_N2_m2r1c2 () Bool
    true)
  (define-fun C_N1_m2r1c2 () Bool
    false)
  (define-fun C_N2_m2r1c1 () Bool
    false)
  (define-fun C_N1_m2r1c1 () Bool
    false)
  (define-fun C_N2_m2r1c0 () Bool
    false)
  (define-fun C_N1_m2r1c0 () Bool
    false)
  (define-fun C_N2_m2r0c6 () Bool
    false)
  (define-fun C_N1_m2r0c6 () Bool
    false)
  (define-fun C_N2_m2r0c5 () Bool
    false)
  (define-fun C_N1_m2r0c5 () Bool
    false)
  (define-fun C_N2_m2r0c4 () Bool
    false)
  (define-fun C_N1_m2r0c4 () Bool
    false)
  (define-fun C_N2_m2r0c3 () Bool
    false)
  (define-fun C_N1_m2r0c3 () Bool
    false)
  (define-fun C_N2_m2r0c2 () Bool
    false)
  (define-fun C_N1_m2r0c2 () Bool
    false)
  (define-fun C_N2_m2r0c1 () Bool
    false)
  (define-fun C_N1_m2r0c1 () Bool
    false)
  (define-fun C_N2_m2r0c0 () Bool
    false)
  (define-fun C_N1_m2r0c0 () Bool
    false)
  (define-fun C_N2_m1r3c6 () Bool
    false)
  (define-fun C_N1_m1r3c6 () Bool
    false)
  (define-fun N1_E_m1r3c6_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r3c6_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r3c5 () Bool
    true)
  (define-fun N2_E_m1r3c5_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m1r3c5_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r3c5 () Bool
    false)
  (define-fun C_N2_m1r3c4 () Bool
    false)
  (define-fun C_N1_m1r3c4 () Bool
    true)
  (define-fun N1_E_m1r3c4_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r3c4_pinMM1_1 () Bool
    true)
  (define-fun C_N2_m1r3c3 () Bool
    true)
  (define-fun N2_E_m1r3c3_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m1r3c3_pinMM1_2 () Bool
    true)
  (define-fun C_N1_m1r3c3 () Bool
    false)
  (define-fun C_N2_m1r3c2 () Bool
    false)
  (define-fun C_N1_m1r3c2 () Bool
    true)
  (define-fun N1_E_m1r3c2_pinMM0_1 () Bool
    true)
  (define-fun N1_E_m1r3c2_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r3c1 () Bool
    false)
  (define-fun N2_E_m1r3c1_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m1r3c1_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r3c1 () Bool
    true)
  (define-fun C_N2_m1r3c0 () Bool
    true)
  (define-fun C_N1_m1r3c0 () Bool
    false)
  (define-fun N1_E_m1r3c0_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r3c0_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r2c6 () Bool
    false)
  (define-fun C_N1_m1r2c6 () Bool
    false)
  (define-fun N1_E_m1r2c6_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r2c6_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r2c5 () Bool
    true)
  (define-fun N2_E_m1r2c5_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r2c5 () Bool
    false)
  (define-fun C_N2_m1r2c4 () Bool
    false)
  (define-fun C_N1_m1r2c4 () Bool
    false)
  (define-fun N1_E_m1r2c4_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r2c3 () Bool
    true)
  (define-fun N2_E_m1r2c3_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r2c3 () Bool
    false)
  (define-fun C_N2_m1r2c2 () Bool
    false)
  (define-fun C_N1_m1r2c2 () Bool
    false)
  (define-fun N1_E_m1r2c2_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r2c1 () Bool
    false)
  (define-fun N2_E_m1r2c1_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r2c1 () Bool
    true)
  (define-fun C_N2_m1r2c0 () Bool
    true)
  (define-fun C_N1_m1r2c0 () Bool
    false)
  (define-fun N1_E_m1r2c0_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r2c0_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r1c6 () Bool
    false)
  (define-fun C_N1_m1r1c6 () Bool
    false)
  (define-fun N1_E_m1r1c6_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r1c6_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r1c5 () Bool
    false)
  (define-fun N2_E_m1r1c5_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r1c5 () Bool
    true)
  (define-fun C_N2_m1r1c4 () Bool
    false)
  (define-fun C_N1_m1r1c4 () Bool
    false)
  (define-fun N1_E_m1r1c4_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r1c3 () Bool
    true)
  (define-fun N2_E_m1r1c3_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r1c3 () Bool
    false)
  (define-fun C_N2_m1r1c2 () Bool
    false)
  (define-fun C_N1_m1r1c2 () Bool
    false)
  (define-fun N1_E_m1r1c2_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r1c1 () Bool
    false)
  (define-fun N2_E_m1r1c1_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r1c1 () Bool
    true)
  (define-fun C_N2_m1r1c0 () Bool
    true)
  (define-fun C_N1_m1r1c0 () Bool
    false)
  (define-fun N1_E_m1r1c0_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r1c0_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r0c6 () Bool
    false)
  (define-fun C_N1_m1r0c6 () Bool
    false)
  (define-fun N1_E_m1r0c6_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r0c6_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r0c5 () Bool
    false)
  (define-fun N2_E_m1r0c5_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m1r0c5_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r0c5 () Bool
    true)
  (define-fun C_N2_m1r0c4 () Bool
    false)
  (define-fun C_N1_m1r0c4 () Bool
    false)
  (define-fun N1_E_m1r0c4_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r0c4_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r0c3 () Bool
    true)
  (define-fun N2_E_m1r0c3_pinMM0_2 () Bool
    true)
  (define-fun N2_E_m1r0c3_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r0c3 () Bool
    false)
  (define-fun C_N2_m1r0c2 () Bool
    false)
  (define-fun C_N1_m1r0c2 () Bool
    false)
  (define-fun N1_E_m1r0c2_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r0c2_pinMM1_1 () Bool
    false)
  (define-fun C_N2_m1r0c1 () Bool
    false)
  (define-fun N2_E_m1r0c1_pinMM0_2 () Bool
    false)
  (define-fun N2_E_m1r0c1_pinMM1_2 () Bool
    false)
  (define-fun C_N1_m1r0c1 () Bool
    false)
  (define-fun C_N2_m1r0c0 () Bool
    true)
  (define-fun C_N1_m1r0c0 () Bool
    false)
  (define-fun N1_E_m1r0c0_pinMM0_1 () Bool
    false)
  (define-fun N1_E_m1r0c0_pinMM1_1 () Bool
    false)
  (define-fun COST_Pin_C6 () Bool
    false)
  (define-fun COST_Pin_C4 () Bool
    false)
  (define-fun COST_Pin_C2 () Bool
    false)
  (define-fun COST_Pin_C0 () Bool
    false)
  (define-fun w1 () (_ BitVec 2)
    #b11)
  (define-fun uw1 () (_ BitVec 2)
    #b10)
  (define-fun nf1 () (_ BitVec 1)
    #b1)
  (define-fun y1 () (_ BitVec 2)
    #b00)
  (define-fun w0 () (_ BitVec 2)
    #b11)
  (define-fun uw0 () (_ BitVec 2)
    #b10)
  (define-fun nf0 () (_ BitVec 1)
    #b1)
  (define-fun y0 () (_ BitVec 2)
    #b00)
)
(objectives
 (COST_SIZE 0)
 ((bvadd (ite (= COST_Pin_C0 true) #b0000001 #b0000000)
       (ite (= COST_Pin_C2 true) #b0000001 #b0000000)
       (ite (= COST_Pin_C4 true) #b0000001 #b0000000)
       (ite (= COST_Pin_C6 true) #b0000001 #b0000000)) 0)
 ((bvadd (ite (= M2_TRACK_0 true) #b001 #b000)
       (ite (= M2_TRACK_1 true) #b001 #b000)
       (ite (= M2_TRACK_2 true) #b001 #b000)
       (ite (= M2_TRACK_3 true) #b001 #b000)) 0)
 ((bvadd (ite (= M_m4r0c0_m4r0c1 true) #x00000001 #x00000000)
       (ite (= M_m4r0c5_m4r0c6 true) #x00000001 #x00000000)
       (ite (= M_m4r1c0_m4r1c1 true) #x00000001 #x00000000)
       (ite (= M_m4r1c5_m4r1c6 true) #x00000001 #x00000000)
       (ite (= M_m4r2c0_m4r2c1 true) #x00000001 #x00000000)
       (ite (= M_m4r2c5_m4r2c6 true) #x00000001 #x00000000)
       (ite (= M_m4r3c0_m4r3c1 true) #x00000001 #x00000000)
       (ite (= M_m4r3c5_m4r3c6 true) #x00000001 #x00000000)
       (ite (= M_m4r0c1_m4r0c2 true) #x00000001 #x00000000)
       (ite (= M_m4r0c4_m4r0c5 true) #x00000001 #x00000000)
       (ite (= M_m4r1c1_m4r1c2 true) #x00000001 #x00000000)
       (ite (= M_m4r1c4_m4r1c5 true) #x00000001 #x00000000)
       (ite (= M_m4r2c1_m4r2c2 true) #x00000001 #x00000000)
       (ite (= M_m4r2c4_m4r2c5 true) #x00000001 #x00000000)
       (ite (= M_m4r3c1_m4r3c2 true) #x00000001 #x00000000)
       (ite (= M_m4r3c4_m4r3c5 true) #x00000001 #x00000000)
       (ite (= M_m4r0c2_m4r0c3 true) #x00000001 #x00000000)
       (ite (= M_m4r0c3_m4r0c4 true) #x00000001 #x00000000)
       (ite (= M_m4r1c2_m4r1c3 true) #x00000001 #x00000000)
       (ite (= M_m4r1c3_m4r1c4 true) #x00000001 #x00000000)
       (ite (= M_m4r2c2_m4r2c3 true) #x00000001 #x00000000)
       (ite (= M_m4r2c3_m4r2c4 true) #x00000001 #x00000000)
       (ite (= M_m4r3c2_m4r3c3 true) #x00000001 #x00000000)
       (ite (= M_m4r3c3_m4r3c4 true) #x00000001 #x00000000)) 0)
 ((bvadd (ite (= M_m3r0c0_m4r0c0 true) #x00000004 #x00000000)
       (ite (= M_m3r0c6_m4r0c6 true) #x00000004 #x00000000)
       (ite (= M_m3r1c0_m4r1c0 true) #x00000004 #x00000000)
       (ite (= M_m3r1c6_m4r1c6 true) #x00000004 #x00000000)
       (ite (= M_m3r2c0_m4r2c0 true) #x00000004 #x00000000)
       (ite (= M_m3r2c6_m4r2c6 true) #x00000004 #x00000000)
       (ite (= M_m3r3c0_m4r3c0 true) #x00000004 #x00000000)
       (ite (= M_m3r3c6_m4r3c6 true) #x00000004 #x00000000)
       (ite (= M_m3r0c2_m4r0c2 true) #x00000004 #x00000000)
       (ite (= M_m3r0c4_m4r0c4 true) #x00000004 #x00000000)
       (ite (= M_m3r1c2_m4r1c2 true) #x00000004 #x00000000)
       (ite (= M_m3r1c4_m4r1c4 true) #x00000004 #x00000000)
       (ite (= M_m3r2c2_m4r2c2 true) #x00000004 #x00000000)
       (ite (= M_m3r2c4_m4r2c4 true) #x00000004 #x00000000)
       (ite (= M_m3r3c2_m4r3c2 true) #x00000004 #x00000000)
       (ite (= M_m3r3c4_m4r3c4 true) #x00000004 #x00000000)) 0)
 ((bvadd (ite (= M_m1r0c0_m2r0c0 true) #x00000004 #x00000000)
       (ite (= M_m1r0c6_m2r0c6 true) #x00000004 #x00000000)
       (ite (= M_m1r1c0_m2r1c0 true) #x00000004 #x00000000)
       (ite (= M_m1r1c6_m2r1c6 true) #x00000004 #x00000000)
       (ite (= M_m1r2c0_m2r2c0 true) #x00000004 #x00000000)
       (ite (= M_m1r2c6_m2r2c6 true) #x00000004 #x00000000)
       (ite (= M_m1r3c0_m2r3c0 true) #x00000004 #x00000000)
       (ite (= M_m1r3c6_m2r3c6 true) #x00000004 #x00000000)
       (ite (= M_m2r0c0_m3r0c0 true) #x00000004 #x00000000)
       (ite (= M_m2r0c6_m3r0c6 true) #x00000004 #x00000000)
       (ite (= M_m2r1c0_m3r1c0 true) #x00000004 #x00000000)
       (ite (= M_m2r1c6_m3r1c6 true) #x00000004 #x00000000)
       (ite (= M_m2r2c0_m3r2c0 true) #x00000004 #x00000000)
       (ite (= M_m2r2c6_m3r2c6 true) #x00000004 #x00000000)
       (ite (= M_m2r3c0_m3r3c0 true) #x00000004 #x00000000)
       (ite (= M_m2r3c6_m3r3c6 true) #x00000004 #x00000000)
       (ite (= M_m1r0c1_m2r0c1 true) #x00000004 #x00000000)
       (ite (= M_m1r0c5_m2r0c5 true) #x00000004 #x00000000)
       (ite (= M_m1r1c1_m2r1c1 true) #x00000004 #x00000000)
       (ite (= M_m1r1c5_m2r1c5 true) #x00000004 #x00000000)
       (ite (= M_m1r2c1_m2r2c1 true) #x00000004 #x00000000)
       (ite (= M_m1r2c5_m2r2c5 true) #x00000004 #x00000000)
       (ite (= M_m1r3c1_m2r3c1 true) #x00000004 #x00000000)
       (ite (= M_m1r3c5_m2r3c5 true) #x00000004 #x00000000)
       (ite (= M_m1r0c2_m2r0c2 true) #x00000004 #x00000000)
       (ite (= M_m1r0c4_m2r0c4 true) #x00000004 #x00000000)
       (ite (= M_m1r1c2_m2r1c2 true) #x00000004 #x00000000)
       (ite (= M_m1r1c4_m2r1c4 true) #x00000004 #x00000000)
       (ite (= M_m1r2c2_m2r2c2 true) #x00000004 #x00000000)
       (ite (= M_m1r2c4_m2r2c4 true) #x00000004 #x00000000)
       (ite (= M_m1r3c2_m2r3c2 true) #x00000004 #x00000000)
       (ite (= M_m1r3c4_m2r3c4 true) #x00000004 #x00000000)
       (ite (= M_m2r0c2_m3r0c2 true) #x00000004 #x00000000)
       (ite (= M_m2r0c4_m3r0c4 true) #x00000004 #x00000000)
       (ite (= M_m2r1c2_m3r1c2 true) #x00000004 #x00000000)
       (ite (= M_m2r1c4_m3r1c4 true) #x00000004 #x00000000)
       (ite (= M_m2r2c2_m3r2c2 true) #x00000004 #x00000000)
       (ite (= M_m2r2c4_m3r2c4 true) #x00000004 #x00000000)
       (ite (= M_m2r3c2_m3r3c2 true) #x00000004 #x00000000)
       (ite (= M_m2r3c4_m3r3c4 true) #x00000004 #x00000000)
       (ite (= M_m1r0c3_m2r0c3 true) #x00000004 #x00000000)
       (ite (= M_m1r1c3_m2r1c3 true) #x00000004 #x00000000)
       (ite (= M_m1r2c3_m2r2c3 true) #x00000004 #x00000000)
       (ite (= M_m1r3c3_m2r3c3 true) #x00000004 #x00000000)) 20)
 ((bvadd (ite (= M_m2r0c0_m2r0c1 true) #x00000001 #x00000000)
       (ite (= M_m2r0c5_m2r0c6 true) #x00000001 #x00000000)
       (ite (= M_m2r1c0_m2r1c1 true) #x00000001 #x00000000)
       (ite (= M_m2r1c5_m2r1c6 true) #x00000001 #x00000000)
       (ite (= M_m2r2c0_m2r2c1 true) #x00000001 #x00000000)
       (ite (= M_m2r2c5_m2r2c6 true) #x00000001 #x00000000)
       (ite (= M_m2r3c0_m2r3c1 true) #x00000001 #x00000000)
       (ite (= M_m2r3c5_m2r3c6 true) #x00000001 #x00000000)
       (ite (= M_m3r0c0_m3r1c0 true) #x00000001 #x00000000)
       (ite (= M_m3r0c6_m3r1c6 true) #x00000001 #x00000000)
       (ite (= M_m3r1c0_m3r2c0 true) #x00000001 #x00000000)
       (ite (= M_m3r1c6_m3r2c6 true) #x00000001 #x00000000)
       (ite (= M_m3r2c0_m3r3c0 true) #x00000001 #x00000000)
       (ite (= M_m3r2c6_m3r3c6 true) #x00000001 #x00000000)
       (ite (= M_m2r0c1_m2r0c2 true) #x00000001 #x00000000)
       (ite (= M_m2r0c4_m2r0c5 true) #x00000001 #x00000000)
       (ite (= M_m2r1c1_m2r1c2 true) #x00000001 #x00000000)
       (ite (= M_m2r1c4_m2r1c5 true) #x00000001 #x00000000)
       (ite (= M_m2r2c1_m2r2c2 true) #x00000001 #x00000000)
       (ite (= M_m2r2c4_m2r2c5 true) #x00000001 #x00000000)
       (ite (= M_m2r3c1_m2r3c2 true) #x00000001 #x00000000)
       (ite (= M_m2r3c4_m2r3c5 true) #x00000001 #x00000000)
       (ite (= M_m2r0c2_m2r0c3 true) #x00000001 #x00000000)
       (ite (= M_m2r0c3_m2r0c4 true) #x00000001 #x00000000)
       (ite (= M_m2r1c2_m2r1c3 true) #x00000001 #x00000000)
       (ite (= M_m2r1c3_m2r1c4 true) #x00000001 #x00000000)
       (ite (= M_m2r2c2_m2r2c3 true) #x00000001 #x00000000)
       (ite (= M_m2r2c3_m2r2c4 true) #x00000001 #x00000000)
       (ite (= M_m2r3c2_m2r3c3 true) #x00000001 #x00000000)
       (ite (= M_m2r3c3_m2r3c4 true) #x00000001 #x00000000)
       (ite (= M_m3r0c2_m3r1c2 true) #x00000001 #x00000000)
       (ite (= M_m3r0c4_m3r1c4 true) #x00000001 #x00000000)
       (ite (= M_m3r1c2_m3r2c2 true) #x00000001 #x00000000)
       (ite (= M_m3r1c4_m3r2c4 true) #x00000001 #x00000000)
       (ite (= M_m3r2c2_m3r3c2 true) #x00000001 #x00000000)
       (ite (= M_m3r2c4_m3r3c4 true) #x00000001 #x00000000)) 9)
 ((bvadd (ite (= M_m1r0c0_m2r0c0 true) #x00000004 #x00000000)
       (ite (= M_m1r0c6_m2r0c6 true) #x00000004 #x00000000)
       (ite (= M_m1r1c0_m2r1c0 true) #x00000004 #x00000000)
       (ite (= M_m1r1c6_m2r1c6 true) #x00000004 #x00000000)
       (ite (= M_m1r2c0_m2r2c0 true) #x00000004 #x00000000)
       (ite (= M_m1r2c6_m2r2c6 true) #x00000004 #x00000000)
       (ite (= M_m1r3c0_m2r3c0 true) #x00000004 #x00000000)
       (ite (= M_m1r3c6_m2r3c6 true) #x00000004 #x00000000)
       (ite (= M_m2r0c0_m2r0c1 true) #x00000001 #x00000000)
       (ite (= M_m2r0c0_m3r0c0 true) #x00000004 #x00000000)
       (ite (= M_m2r0c5_m2r0c6 true) #x00000001 #x00000000)
       (ite (= M_m2r0c6_m3r0c6 true) #x00000004 #x00000000)
       (ite (= M_m2r1c0_m2r1c1 true) #x00000001 #x00000000)
       (ite (= M_m2r1c0_m3r1c0 true) #x00000004 #x00000000)
       (ite (= M_m2r1c5_m2r1c6 true) #x00000001 #x00000000)
       (ite (= M_m2r1c6_m3r1c6 true) #x00000004 #x00000000)
       (ite (= M_m2r2c0_m2r2c1 true) #x00000001 #x00000000)
       (ite (= M_m2r2c0_m3r2c0 true) #x00000004 #x00000000)
       (ite (= M_m2r2c5_m2r2c6 true) #x00000001 #x00000000)
       (ite (= M_m2r2c6_m3r2c6 true) #x00000004 #x00000000)
       (ite (= M_m2r3c0_m2r3c1 true) #x00000001 #x00000000)
       (ite (= M_m2r3c0_m3r3c0 true) #x00000004 #x00000000)
       (ite (= M_m2r3c5_m2r3c6 true) #x00000001 #x00000000)
       (ite (= M_m2r3c6_m3r3c6 true) #x00000004 #x00000000)
       (ite (= M_m3r0c0_m3r1c0 true) #x00000001 #x00000000)
       (ite (= M_m3r0c0_m4r0c0 true) #x00000004 #x00000000)
       (ite (= M_m3r0c6_m3r1c6 true) #x00000001 #x00000000)
       (ite (= M_m3r0c6_m4r0c6 true) #x00000004 #x00000000)
       (ite (= M_m3r1c0_m3r2c0 true) #x00000001 #x00000000)
       (ite (= M_m3r1c0_m4r1c0 true) #x00000004 #x00000000)
       (ite (= M_m3r1c6_m3r2c6 true) #x00000001 #x00000000)
       (ite (= M_m3r1c6_m4r1c6 true) #x00000004 #x00000000)
       (ite (= M_m3r2c0_m3r3c0 true) #x00000001 #x00000000)
       (ite (= M_m3r2c0_m4r2c0 true) #x00000004 #x00000000)
       (ite (= M_m3r2c6_m3r3c6 true) #x00000001 #x00000000)
       (ite (= M_m3r2c6_m4r2c6 true) #x00000004 #x00000000)
       (ite (= M_m3r3c0_m4r3c0 true) #x00000004 #x00000000)
       (ite (= M_m3r3c6_m4r3c6 true) #x00000004 #x00000000)
       (ite (= M_m4r0c0_m4r0c1 true) #x00000001 #x00000000)
       (ite (= M_m4r0c5_m4r0c6 true) #x00000001 #x00000000)
       (ite (= M_m4r1c0_m4r1c1 true) #x00000001 #x00000000)
       (ite (= M_m4r1c5_m4r1c6 true) #x00000001 #x00000000)
       (ite (= M_m4r2c0_m4r2c1 true) #x00000001 #x00000000)
       (ite (= M_m4r2c5_m4r2c6 true) #x00000001 #x00000000)
       (ite (= M_m4r3c0_m4r3c1 true) #x00000001 #x00000000)
       (ite (= M_m4r3c5_m4r3c6 true) #x00000001 #x00000000)
       (ite (= M_m1r0c1_m2r0c1 true) #x00000004 #x00000000)
       (ite (= M_m1r0c5_m2r0c5 true) #x00000004 #x00000000)
       (ite (= M_m1r1c1_m2r1c1 true) #x00000004 #x00000000)
       (ite (= M_m1r1c5_m2r1c5 true) #x00000004 #x00000000)
       (ite (= M_m1r2c1_m2r2c1 true) #x00000004 #x00000000)
       (ite (= M_m1r2c5_m2r2c5 true) #x00000004 #x00000000)
       (ite (= M_m1r3c1_m2r3c1 true) #x00000004 #x00000000)
       (ite (= M_m1r3c5_m2r3c5 true) #x00000004 #x00000000)
       (ite (= M_m2r0c1_m2r0c2 true) #x00000001 #x00000000)
       (ite (= M_m2r0c4_m2r0c5 true) #x00000001 #x00000000)
       (ite (= M_m2r1c1_m2r1c2 true) #x00000001 #x00000000)
       (ite (= M_m2r1c4_m2r1c5 true) #x00000001 #x00000000)
       (ite (= M_m2r2c1_m2r2c2 true) #x00000001 #x00000000)
       (ite (= M_m2r2c4_m2r2c5 true) #x00000001 #x00000000)
       (ite (= M_m2r3c1_m2r3c2 true) #x00000001 #x00000000)
       (ite (= M_m2r3c4_m2r3c5 true) #x00000001 #x00000000)
       (ite (= M_m4r0c1_m4r0c2 true) #x00000001 #x00000000)
       (ite (= M_m4r0c4_m4r0c5 true) #x00000001 #x00000000)
       (ite (= M_m4r1c1_m4r1c2 true) #x00000001 #x00000000)
       (ite (= M_m4r1c4_m4r1c5 true) #x00000001 #x00000000)
       (ite (= M_m4r2c1_m4r2c2 true) #x00000001 #x00000000)
       (ite (= M_m4r2c4_m4r2c5 true) #x00000001 #x00000000)
       (ite (= M_m4r3c1_m4r3c2 true) #x00000001 #x00000000)
       (ite (= M_m4r3c4_m4r3c5 true) #x00000001 #x00000000)
       (ite (= M_m1r0c2_m2r0c2 true) #x00000004 #x00000000)
       (ite (= M_m1r0c4_m2r0c4 true) #x00000004 #x00000000)
       (ite (= M_m1r1c2_m2r1c2 true) #x00000004 #x00000000)
       (ite (= M_m1r1c4_m2r1c4 true) #x00000004 #x00000000)
       (ite (= M_m1r2c2_m2r2c2 true) #x00000004 #x00000000)
       (ite (= M_m1r2c4_m2r2c4 true) #x00000004 #x00000000)
       (ite (= M_m1r3c2_m2r3c2 true) #x00000004 #x00000000)
       (ite (= M_m1r3c4_m2r3c4 true) #x00000004 #x00000000)
       (ite (= M_m2r0c2_m2r0c3 true) #x00000001 #x00000000)
       (ite (= M_m2r0c2_m3r0c2 true) #x00000004 #x00000000)
       (ite (= M_m2r0c3_m2r0c4 true) #x00000001 #x00000000)
       (ite (= M_m2r0c4_m3r0c4 true) #x00000004 #x00000000)
       (ite (= M_m2r1c2_m2r1c3 true) #x00000001 #x00000000)
       (ite (= M_m2r1c2_m3r1c2 true) #x00000004 #x00000000)
       (ite (= M_m2r1c3_m2r1c4 true) #x00000001 #x00000000)
       (ite (= M_m2r1c4_m3r1c4 true) #x00000004 #x00000000)
       (ite (= M_m2r2c2_m2r2c3 true) #x00000001 #x00000000)
       (ite (= M_m2r2c2_m3r2c2 true) #x00000004 #x00000000)
       (ite (= M_m2r2c3_m2r2c4 true) #x00000001 #x00000000)
       (ite (= M_m2r2c4_m3r2c4 true) #x00000004 #x00000000)
       (ite (= M_m2r3c2_m2r3c3 true) #x00000001 #x00000000)
       (ite (= M_m2r3c2_m3r3c2 true) #x00000004 #x00000000)
       (ite (= M_m2r3c3_m2r3c4 true) #x00000001 #x00000000)
       (ite (= M_m2r3c4_m3r3c4 true) #x00000004 #x00000000)
       (ite (= M_m3r0c2_m3r1c2 true) #x00000001 #x00000000)
       (ite (= M_m3r0c2_m4r0c2 true) #x00000004 #x00000000)
       (ite (= M_m3r0c4_m3r1c4 true) #x00000001 #x00000000)
       (ite (= M_m3r0c4_m4r0c4 true) #x00000004 #x00000000)
       (ite (= M_m3r1c2_m3r2c2 true) #x00000001 #x00000000)
       (ite (= M_m3r1c2_m4r1c2 true) #x00000004 #x00000000)
       (ite (= M_m3r1c4_m3r2c4 true) #x00000001 #x00000000)
       (ite (= M_m3r1c4_m4r1c4 true) #x00000004 #x00000000)
       (ite (= M_m3r2c2_m3r3c2 true) #x00000001 #x00000000)
       (ite (= M_m3r2c2_m4r2c2 true) #x00000004 #x00000000)
       (ite (= M_m3r2c4_m3r3c4 true) #x00000001 #x00000000)
       (ite (= M_m3r2c4_m4r2c4 true) #x00000004 #x00000000)
       (ite (= M_m3r3c2_m4r3c2 true) #x00000004 #x00000000)
       (ite (= M_m3r3c4_m4r3c4 true) #x00000004 #x00000000)
       (ite (= M_m4r0c2_m4r0c3 true) #x00000001 #x00000000)
       (ite (= M_m4r0c3_m4r0c4 true) #x00000001 #x00000000)
       (ite (= M_m4r1c2_m4r1c3 true) #x00000001 #x00000000)
       (ite (= M_m4r1c3_m4r1c4 true) #x00000001 #x00000000)
       (ite (= M_m4r2c2_m4r2c3 true) #x00000001 #x00000000)
       (ite (= M_m4r2c3_m4r2c4 true) #x00000001 #x00000000)
       (ite (= M_m4r3c2_m4r3c3 true) #x00000001 #x00000000)
       (ite (= M_m4r3c3_m4r3c4 true) #x00000001 #x00000000)) 25)
)
(:eliminated-vars         462
 :max-memory              56.36
 :memory                  55.98
 :num-allocs              175200106
 :pb-conflicts            18
 :pb-lemmas               3
 :pb-propagations         3484
 :pb-resolves             94
 :pb-subsumes             126
 :rlimit-count            3007702
 :sat-backjumps           2230
 :sat-conflicts           2237
 :sat-decisions           21146
 :sat-del-clause          3594
 :sat-elim-clauses        2399
 :sat-elim-literals       6142
 :sat-minimized-lits      7444
 :sat-mk-clause-2ary      11297
 :sat-mk-clause-3ary      5151
 :sat-mk-clause-nary      2918
 :sat-mk-var              3742
 :sat-probing-assigned    450
 :sat-propagations-2ary   666720
 :sat-propagations-3ary   216915
 :sat-propagations-nary   73424
 :sat-restarts            72
 :sat-scc-elim-binary     153
 :sat-scc-elim-vars       901
 :sat-subs-resolution     696
 :sat-subs-resolution-dyn 310
 :sat-subsumed            525
 :sat-units               1957
 :time                    0.14
 :total-time              0.17)
